# 00 · Carga y consolidación de la cohorte

**Fase CRISP-DM: Comprensión de los datos (inicio).**

El dataset del [PhysioNet/CinC Challenge 2019](https://physionet.org/content/challenge-2019/1.0.0/)
no viene como una tabla, sino como **40.336 archivos `.psv`, uno por paciente**, repartidos en
dos carpetas que corresponden a **dos hospitales distintos** (`training_setA` y `training_setB`).

Cada archivo es una serie temporal: **una fila por hora de estancia en UCI**, con 40 columnas
(signos vitales, laboratorios, demografía) y la etiqueta `SepsisLabel`.

Este notebook tiene un único objetivo: convertir esos 40.336 archivos en **una sola tabla
confiable**, verificando por el camino que los supuestos que vamos a usar en todo el proyecto
son ciertos. No hacemos análisis todavía; hacemos **auditoría de integridad**.

### Dos piezas de información que están fuera de los datos

Antes de cargar, hay que notar algo que es fácil pasar por alto: dentro de cada `.psv` **no
existe ninguna columna que identifique al paciente ni al hospital**. Esa información vive en
el nombre del archivo (`p000001.psv`) y en la carpeta que lo contiene.

Las dos son críticas y hay que rescatarlas al cargar:

- **`pid` (paciente)**: sin él no podemos agrupar las filas por paciente, y sin eso cualquier
  partición train/test mezclaría horas del mismo paciente en ambos lados. Eso sería fuga de
  información y las métricas quedarían infladas. Es el error más grave posible en este dataset.
- **`hosp` (hospital)**: los dos sets provienen de sistemas hospitalarios distintos. Queremos
  medir si un modelo entrenado en uno funciona en el otro, y para eso necesitamos la etiqueta.

In [1]:
import sys
from pathlib import Path

import pandas as pd

sys.path.append(str(Path.cwd().parent / "src"))
import io_datos
from config import cargar_config

cfg = cargar_config()
pd.set_option("display.max_columns", 50)

## 1. Inventario de archivos

Antes de leer 40.336 archivos conviene confirmar que están todos donde esperamos y en qué
proporción, porque un desbalance entre hospitales condicionaría la estrategia de validación.

In [2]:
archivos = io_datos.listar_archivos(cfg)
inventario = pd.Series([h for _, h in archivos]).value_counts().rename("n_pacientes").to_frame()
inventario.assign(porcentaje_=lambda d: (d.n_pacientes / d.n_pacientes.sum() * 100).round(1))

   n_pacientes  porcentaje_
A        20336         50.4
B        20000         49.6

Los dos hospitales aportan prácticamente el mismo número de pacientes, así que cualquier
diferencia que encontremos después **no vendrá del tamaño de muestra** sino de la población o
de la práctica clínica de cada sitio. Es un buen punto de partida para la comparación A vs B.

## 2. Cómo es un archivo por dentro

Miramos un paciente crudo antes de tocar nada. Es la única forma de entender qué significa
una fila y de detectar el patrón de medición real.

In [3]:
ruta_ejemplo, hosp_ejemplo = archivos[0]
ejemplo = pd.read_csv(ruta_ejemplo, sep="|")
print(f"{ruta_ejemplo.name} (hospital {hosp_ejemplo}) — {ejemplo.shape[0]} horas x {ejemplo.shape[1]} columnas")
ejemplo.head(8)

p000001.psv (hospital A) — 54 horas x 41 columnas

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,FiO2,pH,PaCO2,SaO2,AST,BUN,Alkalinephos,Calcium,Chloride,Creatinine,Bilirubin_direct,Glucose,Lactate,Magnesium,Phosphate,Potassium,Bilirubin_total,TroponinI,Hct,Hgb,PTT,WBC,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,1,0
1,97.0,95.0,NaN,98.0,75.33,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,2,0
2,89.0,99.0,NaN,122.0,86.00,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,3,0
3,90.0,95.0,NaN,NaN,NaN,NaN,30.0,NaN,24.0,NaN,NaN,7.36,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,4,0
4,103.0,88.5,NaN,122.0,91.33,NaN,24.5,NaN,NaN,NaN,0.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,5,0
5,110.0,91.0,NaN,NaN,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,6,0
6,108.0,92.0,36.11,123.0,77.00,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,7,0
7,106.0,90.5,NaN,93.0,76.33,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,8,0

Aquí ya aparece el rasgo que define este dataset: **la primera fila está casi completamente
vacía** y las siguientes solo traen algunos signos vitales. Los laboratorios aparecen de forma
esporádica, no cada hora.

Esto no es un defecto de los datos: es el reflejo de cómo funciona una UCI. Los monitores
registran frecuencia cardiaca y saturación de forma continua, pero un laboratorio se solicita
solo cuando el médico decide pedirlo. El patrón de qué se mide y cuándo sería muy interesante de analizar.

Veamos qué tan denso es el registro en este paciente concreto:

In [4]:
# Cuántas mediciones reales tiene cada variable en este paciente, sobre el total de sus horas
densidad_ejemplo = (ejemplo.notna().sum() / len(ejemplo) * 100).round(1).sort_values(ascending=False)
densidad_ejemplo.rename("% de horas con medición").to_frame().T

,SepsisLabel,Age,ICULOS,Gender,HospAdmTime,Resp,HR,O2Sat,MAP,SBP,Temp,BaseExcess,pH,PaCO2,FiO2,SaO2,Platelets,Hgb,Phosphate,Creatinine,Magnesium,HCO3,BUN,Chloride,Calcium,Glucose,Potassium,WBC,Hct,Bilirubin_total,Alkalinephos,AST,DBP,EtCO2,Bilirubin_direct,Lactate,TroponinI,Fibrinogen,PTT,Unit1,Unit2
% de horas con medición,100.0,100.0,100.0,100.0,100.0,92.6,90.7,81.5,77.8,77.8,18.5,13.0,13.0,11.1,7.4,7.4,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,1.9,1.9,1.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 3. Consolidación

Apilamos los 40.336 archivos en una sola tabla en formato largo, añadiendo `pid` y `hosp`.

Dos decisiones de tipos de datos que vale la pena justificar:

- **`float32` en vez de `float64`** para las mediciones: los valores clínicos tienen a lo sumo
  dos decimales, así que `float64` no aporta precisión y duplica la memoria de una tabla de
  ~1,5 millones de filas.
- **`category` para `pid` y `hosp`**: son cadenas repetidas millones de veces; como categoría
  ocupan una fracción y las agrupaciones por paciente son mucho más rápidas.

In [5]:
df = io_datos.cargar_cohorte(cfg)
print(f"{len(df):,} filas-hora | {df.pid.nunique():,} pacientes | {df.shape[1]} columnas")
print(f"Memoria: {df.memory_usage(deep=True).sum() / 1024**2:.0f} MB")

Leyendo pacientes:   0%|          | 0/40336 [00:00<?, ?it/s]

Leyendo pacientes:   0%|          | 22/40336 [00:00<08:17, 80.97it/s]

Leyendo pacientes:   0%|          | 47/40336 [00:00<04:49, 139.09it/s]

Leyendo pacientes:   0%|          | 82/40336 [00:00<03:16, 204.77it/s]

Leyendo pacientes:   0%|          | 113/40336 [00:00<02:50, 236.54it/s]

Leyendo pacientes:   0%|          | 141/40336 [00:00<02:47, 240.03it/s]

Leyendo pacientes:   0%|          | 170/40336 [00:00<02:39, 251.39it/s]

Leyendo pacientes:   0%|          | 199/40336 [00:00<02:32, 262.56it/s]

Leyendo pacientes:   1%|          | 228/40336 [00:01<02:29, 268.46it/s]

Leyendo pacientes:   1%|          | 256/40336 [00:01<02:29, 267.95it/s]

Leyendo pacientes:   1%|          | 287/40336 [00:01<02:23, 278.36it/s]

Leyendo pacientes:   1%|          | 316/40336 [00:01<02:23, 279.37it/s]

Leyendo pacientes:   1%|          | 346/40336 [00:01<02:21, 282.47it/s]

Leyendo pacientes:   1%|          | 375/40336 [00:01<02:20, 283.81it/s]

Leyendo pacientes:   1%|          | 404/40336 [00:01<04:06, 161.82it/s]

Leyendo pacientes:   1%|          | 433/40336 [00:01<03:36, 184.19it/s]

Leyendo pacientes:   1%|          | 460/40336 [00:02<03:19, 200.36it/s]

Leyendo pacientes:   1%|          | 486/40336 [00:02<03:06, 214.11it/s]

Leyendo pacientes:   1%|▏         | 511/40336 [00:02<03:01, 219.88it/s]

Leyendo pacientes:   1%|▏         | 543/40336 [00:02<02:45, 240.99it/s]

Leyendo pacientes:   1%|▏         | 576/40336 [00:02<02:33, 259.66it/s]

Leyendo pacientes:   2%|▏         | 606/40336 [00:02<02:28, 267.37it/s]

Leyendo pacientes:   2%|▏         | 637/40336 [00:02<02:25, 273.32it/s]

Leyendo pacientes:   2%|▏         | 666/40336 [00:02<02:24, 274.94it/s]

Leyendo pacientes:   2%|▏         | 697/40336 [00:02<02:23, 276.49it/s]

Leyendo pacientes:   2%|▏         | 726/40336 [00:03<02:23, 276.63it/s]

Leyendo pacientes:   2%|▏         | 754/40336 [00:03<02:22, 277.52it/s]

Leyendo pacientes:   2%|▏         | 783/40336 [00:03<02:21, 279.27it/s]

Leyendo pacientes:   2%|▏         | 814/40336 [00:03<02:19, 283.63it/s]

Leyendo pacientes:   2%|▏         | 843/40336 [00:03<04:05, 160.92it/s]

Leyendo pacientes:   2%|▏         | 871/40336 [00:03<03:37, 181.27it/s]

Leyendo pacientes:   2%|▏         | 900/40336 [00:03<03:13, 203.43it/s]

Leyendo pacientes:   2%|▏         | 927/40336 [00:04<03:00, 218.45it/s]

Leyendo pacientes:   2%|▏         | 955/40336 [00:04<02:49, 232.09it/s]

Leyendo pacientes:   2%|▏         | 985/40336 [00:04<02:39, 246.24it/s]

Leyendo pacientes:   3%|▎         | 1015/40336 [00:04<02:31, 259.28it/s]

Leyendo pacientes:   3%|▎         | 1043/40336 [00:04<02:29, 263.61it/s]

Leyendo pacientes:   3%|▎         | 1071/40336 [00:04<02:26, 268.21it/s]

Leyendo pacientes:   3%|▎         | 1100/40336 [00:04<02:23, 274.31it/s]

Leyendo pacientes:   3%|▎         | 1129/40336 [00:04<02:21, 277.96it/s]

Leyendo pacientes:   3%|▎         | 1158/40336 [00:04<02:21, 276.65it/s]

Leyendo pacientes:   3%|▎         | 1189/40336 [00:04<02:17, 284.02it/s]

Leyendo pacientes:   3%|▎         | 1218/40336 [00:05<02:18, 281.84it/s]

Leyendo pacientes:   3%|▎         | 1248/40336 [00:05<02:17, 284.78it/s]

Leyendo pacientes:   3%|▎         | 1279/40336 [00:05<02:15, 289.26it/s]

Leyendo pacientes:   3%|▎         | 1309/40336 [00:05<02:19, 280.55it/s]

Leyendo pacientes:   3%|▎         | 1338/40336 [00:05<02:18, 282.13it/s]

Leyendo pacientes:   3%|▎         | 1368/40336 [00:05<02:15, 286.90it/s]

Leyendo pacientes:   3%|▎         | 1397/40336 [00:05<02:17, 282.98it/s]

Leyendo pacientes:   4%|▎         | 1426/40336 [00:06<04:33, 142.42it/s]

Leyendo pacientes:   4%|▎         | 1454/40336 [00:06<03:54, 165.57it/s]

Leyendo pacientes:   4%|▎         | 1483/40336 [00:06<03:25, 189.24it/s]

Leyendo pacientes:   4%|▎         | 1512/40336 [00:06<03:04, 210.67it/s]

Leyendo pacientes:   4%|▍         | 1543/40336 [00:06<02:47, 231.69it/s]

Leyendo pacientes:   4%|▍         | 1571/40336 [00:06<02:39, 243.15it/s]

Leyendo pacientes:   4%|▍         | 1601/40336 [00:06<02:31, 255.13it/s]

Leyendo pacientes:   4%|▍         | 1632/40336 [00:06<02:25, 265.13it/s]

Leyendo pacientes:   4%|▍         | 1662/40336 [00:06<02:20, 274.38it/s]

Leyendo pacientes:   4%|▍         | 1691/40336 [00:07<02:20, 275.74it/s]

Leyendo pacientes:   4%|▍         | 1721/40336 [00:07<02:18, 279.50it/s]

Leyendo pacientes:   4%|▍         | 1750/40336 [00:07<02:16, 282.11it/s]

Leyendo pacientes:   4%|▍         | 1782/40336 [00:07<02:14, 286.32it/s]

Leyendo pacientes:   4%|▍         | 1813/40336 [00:07<02:12, 291.07it/s]

Leyendo pacientes:   5%|▍         | 1843/40336 [00:07<02:12, 290.65it/s]

Leyendo pacientes:   5%|▍         | 1873/40336 [00:07<02:13, 287.23it/s]

Leyendo pacientes:   5%|▍         | 1905/40336 [00:07<02:12, 290.31it/s]

Leyendo pacientes:   5%|▍         | 1937/40336 [00:07<02:11, 292.85it/s]

Leyendo pacientes:   5%|▍         | 1967/40336 [00:07<02:13, 288.09it/s]

Leyendo pacientes:   5%|▍         | 1999/40336 [00:08<02:12, 290.04it/s]

Leyendo pacientes:   5%|▌         | 2029/40336 [00:08<02:15, 283.42it/s]

Leyendo pacientes:   5%|▌         | 2058/40336 [00:08<02:14, 284.54it/s]

Leyendo pacientes:   5%|▌         | 2087/40336 [00:08<02:17, 279.13it/s]

Leyendo pacientes:   5%|▌         | 2115/40336 [00:08<04:41, 135.71it/s]

Leyendo pacientes:   5%|▌         | 2144/40336 [00:09<04:00, 158.99it/s]

Leyendo pacientes:   5%|▌         | 2175/40336 [00:09<03:24, 186.47it/s]

Leyendo pacientes:   5%|▌         | 2205/40336 [00:09<03:01, 210.42it/s]

Leyendo pacientes:   6%|▌         | 2237/40336 [00:09<02:45, 230.25it/s]

Leyendo pacientes:   6%|▌         | 2268/40336 [00:09<02:33, 247.63it/s]

Leyendo pacientes:   6%|▌         | 2300/40336 [00:09<02:25, 261.78it/s]

Leyendo pacientes:   6%|▌         | 2329/40336 [00:09<02:23, 264.14it/s]

Leyendo pacientes:   6%|▌         | 2358/40336 [00:09<02:22, 266.78it/s]

Leyendo pacientes:   6%|▌         | 2387/40336 [00:09<02:19, 272.71it/s]

Leyendo pacientes:   6%|▌         | 2416/40336 [00:09<02:17, 276.53it/s]

Leyendo pacientes:   6%|▌         | 2445/40336 [00:10<02:19, 270.96it/s]

Leyendo pacientes:   6%|▌         | 2474/40336 [00:10<02:18, 272.83it/s]

Leyendo pacientes:   6%|▌         | 2503/40336 [00:10<02:16, 276.24it/s]

Leyendo pacientes:   6%|▋         | 2533/40336 [00:10<02:14, 280.37it/s]

Leyendo pacientes:   6%|▋         | 2563/40336 [00:10<02:12, 285.08it/s]

Leyendo pacientes:   6%|▋         | 2593/40336 [00:10<02:12, 283.99it/s]

Leyendo pacientes:   7%|▋         | 2623/40336 [00:10<02:11, 286.51it/s]

Leyendo pacientes:   7%|▋         | 2652/40336 [00:10<02:12, 285.34it/s]

Leyendo pacientes:   7%|▋         | 2682/40336 [00:10<02:11, 287.40it/s]

Leyendo pacientes:   7%|▋         | 2711/40336 [00:10<02:14, 279.36it/s]

Leyendo pacientes:   7%|▋         | 2740/40336 [00:11<02:14, 278.91it/s]

Leyendo pacientes:   7%|▋         | 2768/40336 [00:11<02:14, 279.18it/s]

Leyendo pacientes:   7%|▋         | 2797/40336 [00:11<02:14, 278.09it/s]

Leyendo pacientes:   7%|▋         | 2825/40336 [00:11<02:15, 277.39it/s]

Leyendo pacientes:   7%|▋         | 2853/40336 [00:11<02:17, 272.98it/s]

Leyendo pacientes:   7%|▋         | 2882/40336 [00:11<02:15, 275.74it/s]

Leyendo pacientes:   7%|▋         | 2913/40336 [00:11<02:11, 283.54it/s]

Leyendo pacientes:   7%|▋         | 2942/40336 [00:11<02:12, 283.07it/s]

Leyendo pacientes:   7%|▋         | 2971/40336 [00:12<05:37, 110.59it/s]

Leyendo pacientes:   7%|▋         | 3002/40336 [00:12<04:32, 136.85it/s]

Leyendo pacientes:   8%|▊         | 3031/40336 [00:12<03:51, 161.00it/s]

Leyendo pacientes:   8%|▊         | 3062/40336 [00:12<03:17, 188.57it/s]

Leyendo pacientes:   8%|▊         | 3092/40336 [00:12<02:56, 210.44it/s]

Leyendo pacientes:   8%|▊         | 3120/40336 [00:12<02:44, 226.42it/s]

Leyendo pacientes:   8%|▊         | 3149/40336 [00:13<02:34, 240.56it/s]

Leyendo pacientes:   8%|▊         | 3178/40336 [00:13<02:26, 253.32it/s]

Leyendo pacientes:   8%|▊         | 3207/40336 [00:13<02:21, 263.06it/s]

Leyendo pacientes:   8%|▊         | 3236/40336 [00:13<02:17, 269.67it/s]

Leyendo pacientes:   8%|▊         | 3265/40336 [00:13<02:14, 275.13it/s]

Leyendo pacientes:   8%|▊         | 3295/40336 [00:13<02:13, 277.12it/s]

Leyendo pacientes:   8%|▊         | 3324/40336 [00:13<02:12, 278.76it/s]

Leyendo pacientes:   8%|▊         | 3353/40336 [00:13<02:15, 272.10it/s]

Leyendo pacientes:   8%|▊         | 3385/40336 [00:13<02:12, 279.17it/s]

Leyendo pacientes:   8%|▊         | 3414/40336 [00:14<02:13, 276.46it/s]

Leyendo pacientes:   9%|▊         | 3444/40336 [00:14<02:12, 279.43it/s]

Leyendo pacientes:   9%|▊         | 3473/40336 [00:14<02:14, 274.09it/s]

Leyendo pacientes:   9%|▊         | 3501/40336 [00:14<02:16, 269.86it/s]

Leyendo pacientes:   9%|▊         | 3529/40336 [00:14<02:17, 267.88it/s]

Leyendo pacientes:   9%|▉         | 3558/40336 [00:14<02:17, 267.91it/s]

Leyendo pacientes:   9%|▉         | 3585/40336 [00:14<02:17, 267.16it/s]

Leyendo pacientes:   9%|▉         | 3612/40336 [00:14<02:17, 267.91it/s]

Leyendo pacientes:   9%|▉         | 3639/40336 [00:14<02:21, 258.48it/s]

Leyendo pacientes:   9%|▉         | 3666/40336 [00:14<02:20, 261.01it/s]

Leyendo pacientes:   9%|▉         | 3695/40336 [00:15<02:17, 266.09it/s]

Leyendo pacientes:   9%|▉         | 3728/40336 [00:15<02:10, 279.54it/s]

Leyendo pacientes:   9%|▉         | 3760/40336 [00:15<02:08, 285.12it/s]

Leyendo pacientes:   9%|▉         | 3791/40336 [00:15<02:07, 286.78it/s]

Leyendo pacientes:   9%|▉         | 3820/40336 [00:15<02:09, 282.69it/s]

Leyendo pacientes:  10%|▉         | 3849/40336 [00:15<02:11, 278.26it/s]

Leyendo pacientes:  10%|▉         | 3878/40336 [00:15<02:10, 280.28it/s]

Leyendo pacientes:  10%|▉         | 3907/40336 [00:15<02:11, 277.60it/s]

Leyendo pacientes:  10%|▉         | 3935/40336 [00:15<02:10, 278.13it/s]

Leyendo pacientes:  10%|▉         | 3963/40336 [00:16<02:10, 278.25it/s]

Leyendo pacientes:  10%|▉         | 3991/40336 [00:16<02:11, 275.55it/s]

Leyendo pacientes:  10%|▉         | 4019/40336 [00:16<02:12, 273.71it/s]

Leyendo pacientes:  10%|█         | 4047/40336 [00:16<06:02, 100.16it/s]

Leyendo pacientes:  10%|█         | 4075/40336 [00:17<04:52, 123.80it/s]

Leyendo pacientes:  10%|█         | 4104/40336 [00:17<04:01, 150.08it/s]

Leyendo pacientes:  10%|█         | 4132/40336 [00:17<03:28, 173.65it/s]

Leyendo pacientes:  10%|█         | 4164/40336 [00:17<03:00, 200.41it/s]

Leyendo pacientes:  10%|█         | 4192/40336 [00:17<02:45, 217.93it/s]

Leyendo pacientes:  10%|█         | 4220/40336 [00:17<02:35, 232.27it/s]

Leyendo pacientes:  11%|█         | 4249/40336 [00:17<02:26, 246.90it/s]

Leyendo pacientes:  11%|█         | 4279/40336 [00:17<02:18, 259.42it/s]

Leyendo pacientes:  11%|█         | 4308/40336 [00:17<02:14, 267.76it/s]

Leyendo pacientes:  11%|█         | 4338/40336 [00:17<02:10, 275.37it/s]

Leyendo pacientes:  11%|█         | 4367/40336 [00:18<02:08, 278.93it/s]

Leyendo pacientes:  11%|█         | 4396/40336 [00:18<02:08, 279.06it/s]

Leyendo pacientes:  11%|█         | 4425/40336 [00:18<02:09, 277.09it/s]

Leyendo pacientes:  11%|█         | 4454/40336 [00:18<02:08, 279.83it/s]

Leyendo pacientes:  11%|█         | 4483/40336 [00:18<02:07, 280.31it/s]

Leyendo pacientes:  11%|█         | 4514/40336 [00:18<02:06, 283.82it/s]

Leyendo pacientes:  11%|█▏        | 4544/40336 [00:18<02:05, 284.48it/s]

Leyendo pacientes:  11%|█▏        | 4575/40336 [00:18<02:04, 286.82it/s]

Leyendo pacientes:  11%|█▏        | 4604/40336 [00:18<02:06, 283.29it/s]

Leyendo pacientes:  11%|█▏        | 4633/40336 [00:18<02:10, 274.26it/s]

Leyendo pacientes:  12%|█▏        | 4662/40336 [00:19<02:08, 277.33it/s]

Leyendo pacientes:  12%|█▏        | 4691/40336 [00:19<02:07, 279.85it/s]

Leyendo pacientes:  12%|█▏        | 4720/40336 [00:19<02:08, 277.83it/s]

Leyendo pacientes:  12%|█▏        | 4748/40336 [00:19<02:08, 276.91it/s]

Leyendo pacientes:  12%|█▏        | 4777/40336 [00:19<02:09, 274.29it/s]

Leyendo pacientes:  12%|█▏        | 4806/40336 [00:19<02:09, 274.43it/s]

Leyendo pacientes:  12%|█▏        | 4835/40336 [00:19<02:08, 276.78it/s]

Leyendo pacientes:  12%|█▏        | 4863/40336 [00:19<02:08, 276.31it/s]

Leyendo pacientes:  12%|█▏        | 4892/40336 [00:19<02:06, 280.09it/s]

Leyendo pacientes:  12%|█▏        | 4922/40336 [00:20<02:06, 279.53it/s]

Leyendo pacientes:  12%|█▏        | 4952/40336 [00:20<02:06, 280.12it/s]

Leyendo pacientes:  12%|█▏        | 4981/40336 [00:20<02:08, 274.63it/s]

Leyendo pacientes:  12%|█▏        | 5009/40336 [00:20<02:18, 255.20it/s]

Leyendo pacientes:  12%|█▏        | 5039/40336 [00:20<02:14, 262.67it/s]

Leyendo pacientes:  13%|█▎        | 5069/40336 [00:20<02:10, 270.58it/s]

Leyendo pacientes:  13%|█▎        | 5099/40336 [00:20<02:06, 278.20it/s]

Leyendo pacientes:  13%|█▎        | 5128/40336 [00:20<02:06, 278.14it/s]

Leyendo pacientes:  13%|█▎        | 5156/40336 [00:20<02:11, 266.98it/s]

Leyendo pacientes:  13%|█▎        | 5187/40336 [00:21<02:08, 274.31it/s]

Leyendo pacientes:  13%|█▎        | 5219/40336 [00:21<02:05, 280.86it/s]

Leyendo pacientes:  13%|█▎        | 5249/40336 [00:21<02:04, 281.84it/s]

Leyendo pacientes:  13%|█▎        | 5278/40336 [00:21<02:04, 282.36it/s]

Leyendo pacientes:  13%|█▎        | 5307/40336 [00:21<02:06, 277.02it/s]

Leyendo pacientes:  13%|█▎        | 5336/40336 [00:21<02:04, 280.15it/s]

Leyendo pacientes:  13%|█▎        | 5365/40336 [00:21<02:08, 272.64it/s]

Leyendo pacientes:  13%|█▎        | 5394/40336 [00:21<02:08, 272.79it/s]

Leyendo pacientes:  13%|█▎        | 5422/40336 [00:22<06:58, 83.34it/s]

Leyendo pacientes:  14%|█▎        | 5450/40336 [00:22<05:32, 105.00it/s]

Leyendo pacientes:  14%|█▎        | 5479/40336 [00:22<04:28, 130.05it/s]

Leyendo pacientes:  14%|█▎        | 5508/40336 [00:22<03:44, 155.31it/s]

Leyendo pacientes:  14%|█▎        | 5537/40336 [00:23<03:13, 180.18it/s]

Leyendo pacientes:  14%|█▍        | 5566/40336 [00:23<02:52, 202.05it/s]

Leyendo pacientes:  14%|█▍        | 5594/40336 [00:23<02:38, 218.89it/s]

Leyendo pacientes:  14%|█▍        | 5625/40336 [00:23<02:25, 239.24it/s]

Leyendo pacientes:  14%|█▍        | 5653/40336 [00:23<02:19, 248.39it/s]

Leyendo pacientes:  14%|█▍        | 5682/40336 [00:23<02:14, 258.06it/s]

Leyendo pacientes:  14%|█▍        | 5711/40336 [00:23<02:10, 265.91it/s]

Leyendo pacientes:  14%|█▍        | 5741/40336 [00:23<02:05, 275.40it/s]

Leyendo pacientes:  14%|█▍        | 5770/40336 [00:23<02:11, 263.66it/s]

Leyendo pacientes:  14%|█▍        | 5798/40336 [00:24<02:10, 264.08it/s]

Leyendo pacientes:  14%|█▍        | 5828/40336 [00:24<02:07, 270.13it/s]

Leyendo pacientes:  15%|█▍        | 5856/40336 [00:24<02:24, 238.86it/s]

Leyendo pacientes:  15%|█▍        | 5881/40336 [00:24<02:26, 234.98it/s]

Leyendo pacientes:  15%|█▍        | 5906/40336 [00:24<02:41, 213.82it/s]

Leyendo pacientes:  15%|█▍        | 5934/40336 [00:24<02:32, 226.00it/s]

Leyendo pacientes:  15%|█▍        | 5961/40336 [00:24<02:25, 235.72it/s]

Leyendo pacientes:  15%|█▍        | 5988/40336 [00:24<02:22, 241.33it/s]

Leyendo pacientes:  15%|█▍        | 6014/40336 [00:24<02:19, 246.35it/s]

Leyendo pacientes:  15%|█▍        | 6045/40336 [00:25<02:09, 264.10it/s]

Leyendo pacientes:  15%|█▌        | 6077/40336 [00:25<02:03, 276.88it/s]

Leyendo pacientes:  15%|█▌        | 6110/40336 [00:25<01:58, 288.80it/s]

Leyendo pacientes:  15%|█▌        | 6141/40336 [00:25<01:56, 294.67it/s]

Leyendo pacientes:  15%|█▌        | 6171/40336 [00:25<01:57, 291.66it/s]

Leyendo pacientes:  15%|█▌        | 6201/40336 [00:25<01:56, 293.36it/s]

Leyendo pacientes:  15%|█▌        | 6233/40336 [00:25<01:53, 299.51it/s]

Leyendo pacientes:  16%|█▌        | 6264/40336 [00:25<01:56, 292.34it/s]

Leyendo pacientes:  16%|█▌        | 6296/40336 [00:25<01:53, 299.06it/s]

Leyendo pacientes:  16%|█▌        | 6326/40336 [00:25<01:58, 286.15it/s]

Leyendo pacientes:  16%|█▌        | 6355/40336 [00:26<01:58, 287.21it/s]

Leyendo pacientes:  16%|█▌        | 6384/40336 [00:26<01:59, 283.91it/s]

Leyendo pacientes:  16%|█▌        | 6413/40336 [00:26<01:58, 285.56it/s]

Leyendo pacientes:  16%|█▌        | 6443/40336 [00:26<01:59, 284.26it/s]

Leyendo pacientes:  16%|█▌        | 6472/40336 [00:26<02:00, 281.28it/s]

Leyendo pacientes:  16%|█▌        | 6501/40336 [00:26<02:02, 276.28it/s]

Leyendo pacientes:  16%|█▌        | 6530/40336 [00:26<02:01, 279.04it/s]

Leyendo pacientes:  16%|█▋        | 6563/40336 [00:26<01:57, 287.81it/s]

Leyendo pacientes:  16%|█▋        | 6592/40336 [00:26<01:57, 288.26it/s]

Leyendo pacientes:  16%|█▋        | 6622/40336 [00:27<01:57, 286.49it/s]

Leyendo pacientes:  16%|█▋        | 6654/40336 [00:27<01:55, 290.37it/s]

Leyendo pacientes:  17%|█▋        | 6684/40336 [00:27<01:57, 286.63it/s]

Leyendo pacientes:  17%|█▋        | 6713/40336 [00:27<01:58, 284.55it/s]

Leyendo pacientes:  17%|█▋        | 6742/40336 [00:27<02:00, 279.85it/s]

Leyendo pacientes:  17%|█▋        | 6772/40336 [00:27<01:59, 281.26it/s]

Leyendo pacientes:  17%|█▋        | 6801/40336 [00:27<02:00, 278.95it/s]

Leyendo pacientes:  17%|█▋        | 6830/40336 [00:27<01:59, 280.06it/s]

Leyendo pacientes:  17%|█▋        | 6861/40336 [00:27<01:56, 286.57it/s]

Leyendo pacientes:  17%|█▋        | 6890/40336 [00:27<01:56, 287.32it/s]

Leyendo pacientes:  17%|█▋        | 6919/40336 [00:28<01:58, 282.61it/s]

Leyendo pacientes:  17%|█▋        | 6949/40336 [00:28<01:56, 286.41it/s]

Leyendo pacientes:  17%|█▋        | 6978/40336 [00:28<01:58, 282.57it/s]

Leyendo pacientes:  17%|█▋        | 7008/40336 [00:28<01:56, 286.74it/s]

Leyendo pacientes:  17%|█▋        | 7038/40336 [00:28<01:56, 284.68it/s]

Leyendo pacientes:  18%|█▊        | 7067/40336 [00:28<01:57, 283.38it/s]

Leyendo pacientes:  18%|█▊        | 7096/40336 [00:29<07:07, 77.82it/s]

Leyendo pacientes:  18%|█▊        | 7126/40336 [00:29<05:32, 99.82it/s]

Leyendo pacientes:  18%|█▊        | 7154/40336 [00:29<04:31, 122.22it/s]

Leyendo pacientes:  18%|█▊        | 7184/40336 [00:29<03:42, 148.85it/s]

Leyendo pacientes:  18%|█▊        | 7211/40336 [00:30<03:16, 168.62it/s]

Leyendo pacientes:  18%|█▊        | 7242/40336 [00:30<02:50, 194.49it/s]

Leyendo pacientes:  18%|█▊        | 7271/40336 [00:30<02:35, 212.48it/s]

Leyendo pacientes:  18%|█▊        | 7298/40336 [00:30<02:27, 223.72it/s]

Leyendo pacientes:  18%|█▊        | 7325/40336 [00:30<02:20, 234.71it/s]

Leyendo pacientes:  18%|█▊        | 7352/40336 [00:30<02:20, 235.14it/s]

Leyendo pacientes:  18%|█▊        | 7379/40336 [00:30<02:15, 243.98it/s]

Leyendo pacientes:  18%|█▊        | 7407/40336 [00:30<02:09, 253.75it/s]

Leyendo pacientes:  18%|█▊        | 7437/40336 [00:30<02:03, 266.26it/s]

Leyendo pacientes:  19%|█▊        | 7467/40336 [00:30<02:00, 273.49it/s]

Leyendo pacientes:  19%|█▊        | 7496/40336 [00:31<01:58, 278.09it/s]

Leyendo pacientes:  19%|█▊        | 7527/40336 [00:31<01:55, 283.50it/s]

Leyendo pacientes:  19%|█▊        | 7558/40336 [00:31<01:53, 288.13it/s]

Leyendo pacientes:  19%|█▉        | 7588/40336 [00:31<01:53, 288.88it/s]

Leyendo pacientes:  19%|█▉        | 7618/40336 [00:31<01:52, 290.34it/s]

Leyendo pacientes:  19%|█▉        | 7648/40336 [00:31<01:51, 291.94it/s]

Leyendo pacientes:  19%|█▉        | 7678/40336 [00:31<01:51, 292.86it/s]

Leyendo pacientes:  19%|█▉        | 7708/40336 [00:31<01:51, 292.62it/s]

Leyendo pacientes:  19%|█▉        | 7740/40336 [00:31<01:48, 299.16it/s]

Leyendo pacientes:  19%|█▉        | 7770/40336 [00:31<01:50, 293.47it/s]

Leyendo pacientes:  19%|█▉        | 7800/40336 [00:32<01:54, 284.42it/s]

Leyendo pacientes:  19%|█▉        | 7831/40336 [00:32<01:51, 290.38it/s]

Leyendo pacientes:  19%|█▉        | 7861/40336 [00:32<01:53, 286.79it/s]

Leyendo pacientes:  20%|█▉        | 7890/40336 [00:32<01:53, 285.00it/s]

Leyendo pacientes:  20%|█▉        | 7919/40336 [00:32<01:56, 278.58it/s]

Leyendo pacientes:  20%|█▉        | 7951/40336 [00:32<01:51, 289.30it/s]

Leyendo pacientes:  20%|█▉        | 7980/40336 [00:32<01:52, 288.72it/s]

Leyendo pacientes:  20%|█▉        | 8011/40336 [00:32<01:50, 292.13it/s]

Leyendo pacientes:  20%|█▉        | 8041/40336 [00:32<01:50, 291.22it/s]

Leyendo pacientes:  20%|██        | 8071/40336 [00:33<01:52, 285.83it/s]

Leyendo pacientes:  20%|██        | 8100/40336 [00:33<01:53, 285.15it/s]

Leyendo pacientes:  20%|██        | 8132/40336 [00:33<01:51, 288.38it/s]

Leyendo pacientes:  20%|██        | 8161/40336 [00:33<01:51, 288.63it/s]

Leyendo pacientes:  20%|██        | 8190/40336 [00:33<01:52, 285.70it/s]

Leyendo pacientes:  20%|██        | 8219/40336 [00:33<01:53, 281.90it/s]

Leyendo pacientes:  20%|██        | 8248/40336 [00:33<01:52, 284.03it/s]

Leyendo pacientes:  21%|██        | 8278/40336 [00:33<01:52, 283.95it/s]

Leyendo pacientes:  21%|██        | 8309/40336 [00:33<01:52, 285.05it/s]

Leyendo pacientes:  21%|██        | 8339/40336 [00:33<01:52, 283.26it/s]

Leyendo pacientes:  21%|██        | 8370/40336 [00:34<01:52, 284.32it/s]

Leyendo pacientes:  21%|██        | 8400/40336 [00:34<01:52, 283.50it/s]

Leyendo pacientes:  21%|██        | 8430/40336 [00:34<01:52, 283.95it/s]

Leyendo pacientes:  21%|██        | 8459/40336 [00:34<01:52, 282.17it/s]

Leyendo pacientes:  21%|██        | 8488/40336 [00:34<01:53, 280.89it/s]

Leyendo pacientes:  21%|██        | 8517/40336 [00:34<01:53, 280.22it/s]

Leyendo pacientes:  21%|██        | 8546/40336 [00:34<01:54, 278.17it/s]

Leyendo pacientes:  21%|██▏       | 8578/40336 [00:34<01:51, 284.55it/s]

Leyendo pacientes:  21%|██▏       | 8607/40336 [00:34<01:52, 280.92it/s]

Leyendo pacientes:  21%|██▏       | 8636/40336 [00:35<01:54, 277.70it/s]

Leyendo pacientes:  21%|██▏       | 8665/40336 [00:35<01:53, 278.69it/s]

Leyendo pacientes:  22%|██▏       | 8695/40336 [00:35<01:51, 282.97it/s]

Leyendo pacientes:  22%|██▏       | 8724/40336 [00:35<01:52, 280.39it/s]

Leyendo pacientes:  22%|██▏       | 8754/40336 [00:35<01:53, 279.18it/s]

Leyendo pacientes:  22%|██▏       | 8785/40336 [00:35<01:51, 282.75it/s]

Leyendo pacientes:  22%|██▏       | 8814/40336 [00:35<01:50, 284.31it/s]

Leyendo pacientes:  22%|██▏       | 8843/40336 [00:35<01:51, 283.09it/s]

Leyendo pacientes:  22%|██▏       | 8872/40336 [00:35<01:52, 280.10it/s]

Leyendo pacientes:  22%|██▏       | 8901/40336 [00:35<01:53, 277.67it/s]

Leyendo pacientes:  22%|██▏       | 8930/40336 [00:36<01:52, 279.43it/s]

Leyendo pacientes:  22%|██▏       | 8958/40336 [00:36<01:54, 274.56it/s]

Leyendo pacientes:  22%|██▏       | 8988/40336 [00:36<01:51, 280.58it/s]

Leyendo pacientes:  22%|██▏       | 9017/40336 [00:36<01:50, 282.63it/s]

Leyendo pacientes:  22%|██▏       | 9046/40336 [00:36<01:50, 283.07it/s]

Leyendo pacientes:  22%|██▏       | 9075/40336 [00:36<01:51, 280.73it/s]

Leyendo pacientes:  23%|██▎       | 9104/40336 [00:36<01:52, 278.35it/s]

Leyendo pacientes:  23%|██▎       | 9135/40336 [00:36<01:50, 281.60it/s]

Leyendo pacientes:  23%|██▎       | 9165/40336 [00:36<01:50, 281.62it/s]

Leyendo pacientes:  23%|██▎       | 9194/40336 [00:38<07:53, 65.83it/s]

Leyendo pacientes:  23%|██▎       | 9224/40336 [00:38<06:01, 85.97it/s]

Leyendo pacientes:  23%|██▎       | 9252/40336 [00:38<04:49, 107.38it/s]

Leyendo pacientes:  23%|██▎       | 9279/40336 [00:38<04:00, 128.90it/s]

Leyendo pacientes:  23%|██▎       | 9307/40336 [00:38<03:24, 152.05it/s]

Leyendo pacientes:  23%|██▎       | 9335/40336 [00:38<02:57, 174.30it/s]

Leyendo pacientes:  23%|██▎       | 9361/40336 [00:38<02:42, 191.02it/s]

Leyendo pacientes:  23%|██▎       | 9388/40336 [00:38<02:28, 207.90it/s]

Leyendo pacientes:  23%|██▎       | 9415/40336 [00:39<02:18, 222.69it/s]

Leyendo pacientes:  23%|██▎       | 9445/40336 [00:39<02:07, 242.52it/s]

Leyendo pacientes:  23%|██▎       | 9476/40336 [00:39<02:00, 255.38it/s]

Leyendo pacientes:  24%|██▎       | 9504/40336 [00:39<01:58, 261.28it/s]

Leyendo pacientes:  24%|██▎       | 9533/40336 [00:39<01:55, 266.64it/s]

Leyendo pacientes:  24%|██▎       | 9563/40336 [00:39<01:51, 275.64it/s]

Leyendo pacientes:  24%|██▍       | 9592/40336 [00:39<01:51, 276.32it/s]

Leyendo pacientes:  24%|██▍       | 9621/40336 [00:39<01:50, 278.80it/s]

Leyendo pacientes:  24%|██▍       | 9650/40336 [00:39<01:51, 275.14it/s]

Leyendo pacientes:  24%|██▍       | 9678/40336 [00:39<01:55, 266.01it/s]

Leyendo pacientes:  24%|██▍       | 9708/40336 [00:40<01:52, 271.31it/s]

Leyendo pacientes:  24%|██▍       | 9738/40336 [00:40<01:49, 279.18it/s]

Leyendo pacientes:  24%|██▍       | 9769/40336 [00:40<01:47, 283.11it/s]

Leyendo pacientes:  24%|██▍       | 9798/40336 [00:40<01:50, 275.13it/s]

Leyendo pacientes:  24%|██▍       | 9826/40336 [00:40<01:50, 275.63it/s]

Leyendo pacientes:  24%|██▍       | 9855/40336 [00:40<01:51, 274.40it/s]

Leyendo pacientes:  25%|██▍       | 9884/40336 [00:40<01:51, 272.57it/s]

Leyendo pacientes:  25%|██▍       | 9915/40336 [00:40<01:49, 277.06it/s]

Leyendo pacientes:  25%|██▍       | 9945/40336 [00:40<01:49, 278.81it/s]

Leyendo pacientes:  25%|██▍       | 9974/40336 [00:41<01:50, 275.48it/s]

Leyendo pacientes:  25%|██▍       | 10002/40336 [00:41<01:49, 276.38it/s]

Leyendo pacientes:  25%|██▍       | 10032/40336 [00:41<01:48, 279.87it/s]

Leyendo pacientes:  25%|██▍       | 10061/40336 [00:41<01:47, 281.60it/s]

Leyendo pacientes:  25%|██▌       | 10090/40336 [00:41<01:47, 280.71it/s]

Leyendo pacientes:  25%|██▌       | 10119/40336 [00:41<01:48, 278.96it/s]

Leyendo pacientes:  25%|██▌       | 10147/40336 [00:41<01:50, 273.90it/s]

Leyendo pacientes:  25%|██▌       | 10180/40336 [00:41<01:45, 284.85it/s]

Leyendo pacientes:  25%|██▌       | 10211/40336 [00:41<01:44, 289.43it/s]

Leyendo pacientes:  25%|██▌       | 10241/40336 [00:41<01:42, 292.25it/s]

Leyendo pacientes:  25%|██▌       | 10271/40336 [00:42<01:44, 288.39it/s]

Leyendo pacientes:  26%|██▌       | 10302/40336 [00:42<01:43, 289.06it/s]

Leyendo pacientes:  26%|██▌       | 10331/40336 [00:42<01:45, 283.62it/s]

Leyendo pacientes:  26%|██▌       | 10360/40336 [00:42<01:47, 279.80it/s]

Leyendo pacientes:  26%|██▌       | 10390/40336 [00:42<01:46, 282.15it/s]

Leyendo pacientes:  26%|██▌       | 10419/40336 [00:42<01:46, 281.88it/s]

Leyendo pacientes:  26%|██▌       | 10448/40336 [00:42<01:46, 281.81it/s]

Leyendo pacientes:  26%|██▌       | 10478/40336 [00:42<01:45, 281.80it/s]

Leyendo pacientes:  26%|██▌       | 10507/40336 [00:42<01:46, 279.30it/s]

Leyendo pacientes:  26%|██▌       | 10535/40336 [00:43<01:49, 272.85it/s]

Leyendo pacientes:  26%|██▌       | 10564/40336 [00:43<01:47, 277.56it/s]

Leyendo pacientes:  26%|██▋       | 10596/40336 [00:43<01:43, 286.77it/s]

Leyendo pacientes:  26%|██▋       | 10627/40336 [00:43<01:42, 291.05it/s]

Leyendo pacientes:  26%|██▋       | 10657/40336 [00:43<01:42, 289.71it/s]

Leyendo pacientes:  26%|██▋       | 10686/40336 [00:43<01:42, 288.23it/s]

Leyendo pacientes:  27%|██▋       | 10715/40336 [00:43<01:45, 280.68it/s]

Leyendo pacientes:  27%|██▋       | 10746/40336 [00:43<01:43, 284.68it/s]

Leyendo pacientes:  27%|██▋       | 10776/40336 [00:43<01:43, 285.48it/s]

Leyendo pacientes:  27%|██▋       | 10809/40336 [00:43<01:41, 291.77it/s]

Leyendo pacientes:  27%|██▋       | 10839/40336 [00:44<01:44, 282.67it/s]

Leyendo pacientes:  27%|██▋       | 10869/40336 [00:44<01:43, 283.35it/s]

Leyendo pacientes:  27%|██▋       | 10900/40336 [00:44<01:42, 287.31it/s]

Leyendo pacientes:  27%|██▋       | 10929/40336 [00:44<01:47, 274.71it/s]

Leyendo pacientes:  27%|██▋       | 10958/40336 [00:44<01:46, 276.91it/s]

Leyendo pacientes:  27%|██▋       | 10987/40336 [00:44<01:44, 280.25it/s]

Leyendo pacientes:  27%|██▋       | 11016/40336 [00:44<01:45, 276.91it/s]

Leyendo pacientes:  27%|██▋       | 11044/40336 [00:44<01:46, 275.79it/s]

Leyendo pacientes:  27%|██▋       | 11074/40336 [00:44<01:44, 280.27it/s]

Leyendo pacientes:  28%|██▊       | 11104/40336 [00:45<01:44, 278.89it/s]

Leyendo pacientes:  28%|██▊       | 11132/40336 [00:45<01:44, 278.31it/s]

Leyendo pacientes:  28%|██▊       | 11161/40336 [00:45<01:44, 279.41it/s]

Leyendo pacientes:  28%|██▊       | 11191/40336 [00:45<01:42, 284.40it/s]

Leyendo pacientes:  28%|██▊       | 11220/40336 [00:45<01:42, 283.41it/s]

Leyendo pacientes:  28%|██▊       | 11249/40336 [00:45<01:43, 280.43it/s]

Leyendo pacientes:  28%|██▊       | 11278/40336 [00:45<01:45, 275.32it/s]

Leyendo pacientes:  28%|██▊       | 11307/40336 [00:45<01:44, 276.82it/s]

Leyendo pacientes:  28%|██▊       | 11336/40336 [00:45<01:43, 279.50it/s]

Leyendo pacientes:  28%|██▊       | 11368/40336 [00:45<01:41, 286.17it/s]

Leyendo pacientes:  28%|██▊       | 11397/40336 [00:46<01:42, 282.51it/s]

Leyendo pacientes:  28%|██▊       | 11426/40336 [00:46<01:41, 284.22it/s]

Leyendo pacientes:  28%|██▊       | 11457/40336 [00:46<01:40, 288.00it/s]

Leyendo pacientes:  28%|██▊       | 11486/40336 [00:46<01:40, 287.86it/s]

Leyendo pacientes:  29%|██▊       | 11515/40336 [00:46<01:44, 276.61it/s]

Leyendo pacientes:  29%|██▊       | 11543/40336 [00:46<01:45, 273.30it/s]

Leyendo pacientes:  29%|██▊       | 11571/40336 [00:46<01:47, 267.45it/s]

Leyendo pacientes:  29%|██▉       | 11599/40336 [00:46<01:46, 269.80it/s]

Leyendo pacientes:  29%|██▉       | 11627/40336 [00:46<01:47, 266.01it/s]

Leyendo pacientes:  29%|██▉       | 11654/40336 [00:47<01:49, 262.84it/s]

Leyendo pacientes:  29%|██▉       | 11681/40336 [00:47<01:49, 261.23it/s]

Leyendo pacientes:  29%|██▉       | 11712/40336 [00:47<01:46, 269.53it/s]

Leyendo pacientes:  29%|██▉       | 11745/40336 [00:47<01:42, 280.27it/s]

Leyendo pacientes:  29%|██▉       | 11775/40336 [00:47<01:41, 281.24it/s]

Leyendo pacientes:  29%|██▉       | 11804/40336 [00:47<01:41, 281.69it/s]

Leyendo pacientes:  29%|██▉       | 11833/40336 [00:48<07:58, 59.62it/s]

Leyendo pacientes:  29%|██▉       | 11860/40336 [00:49<06:14, 76.05it/s]

Leyendo pacientes:  29%|██▉       | 11886/40336 [00:49<05:00, 94.76it/s]

Leyendo pacientes:  30%|██▉       | 11914/40336 [00:49<04:00, 118.15it/s]

Leyendo pacientes:  30%|██▉       | 11944/40336 [00:49<03:15, 145.27it/s]

Leyendo pacientes:  30%|██▉       | 11975/40336 [00:49<02:42, 174.35it/s]

Leyendo pacientes:  30%|██▉       | 12005/40336 [00:49<02:23, 197.64it/s]

Leyendo pacientes:  30%|██▉       | 12033/40336 [00:49<02:11, 215.63it/s]

Leyendo pacientes:  30%|██▉       | 12064/40336 [00:49<01:59, 235.97it/s]

Leyendo pacientes:  30%|██▉       | 12093/40336 [00:49<01:54, 246.29it/s]

Leyendo pacientes:  30%|███       | 12123/40336 [00:49<01:50, 256.23it/s]

Leyendo pacientes:  30%|███       | 12154/40336 [00:50<01:46, 263.87it/s]

Leyendo pacientes:  30%|███       | 12187/40336 [00:50<01:41, 277.18it/s]

Leyendo pacientes:  30%|███       | 12217/40336 [00:50<01:41, 276.56it/s]

Leyendo pacientes:  30%|███       | 12246/40336 [00:50<01:41, 275.78it/s]

Leyendo pacientes:  30%|███       | 12275/40336 [00:50<01:41, 276.93it/s]

Leyendo pacientes:  31%|███       | 12304/40336 [00:50<01:41, 275.37it/s]

Leyendo pacientes:  31%|███       | 12333/40336 [00:50<01:40, 278.23it/s]

Leyendo pacientes:  31%|███       | 12363/40336 [00:50<01:39, 282.46it/s]

Leyendo pacientes:  31%|███       | 12393/40336 [00:50<01:38, 282.28it/s]

Leyendo pacientes:  31%|███       | 12422/40336 [00:51<01:40, 276.69it/s]

Leyendo pacientes:  31%|███       | 12450/40336 [00:51<01:40, 277.60it/s]

Leyendo pacientes:  31%|███       | 12478/40336 [00:51<01:40, 277.14it/s]

Leyendo pacientes:  31%|███       | 12509/40336 [00:51<01:38, 281.42it/s]

Leyendo pacientes:  31%|███       | 12543/40336 [00:51<01:35, 292.27it/s]

Leyendo pacientes:  31%|███       | 12574/40336 [00:51<01:35, 291.63it/s]

Leyendo pacientes:  31%|███       | 12604/40336 [00:51<01:48, 255.05it/s]

Leyendo pacientes:  31%|███▏      | 12631/40336 [00:51<01:51, 248.44it/s]

Leyendo pacientes:  31%|███▏      | 12658/40336 [00:51<01:49, 252.83it/s]

Leyendo pacientes:  31%|███▏      | 12684/40336 [00:52<01:52, 246.40it/s]

Leyendo pacientes:  32%|███▏      | 12715/40336 [00:52<01:46, 258.96it/s]

Leyendo pacientes:  32%|███▏      | 12745/40336 [00:52<01:43, 267.71it/s]

Leyendo pacientes:  32%|███▏      | 12772/40336 [00:52<01:43, 267.08it/s]

Leyendo pacientes:  32%|███▏      | 12800/40336 [00:52<01:41, 270.33it/s]

Leyendo pacientes:  32%|███▏      | 12828/40336 [00:52<01:44, 263.77it/s]

Leyendo pacientes:  32%|███▏      | 12855/40336 [00:52<01:47, 255.12it/s]

Leyendo pacientes:  32%|███▏      | 12882/40336 [00:52<01:46, 256.81it/s]

Leyendo pacientes:  32%|███▏      | 12911/40336 [00:52<01:44, 262.79it/s]

Leyendo pacientes:  32%|███▏      | 12938/40336 [00:52<01:43, 264.53it/s]

Leyendo pacientes:  32%|███▏      | 12965/40336 [00:53<01:45, 259.43it/s]

Leyendo pacientes:  32%|███▏      | 12991/40336 [00:53<01:49, 250.84it/s]

Leyendo pacientes:  32%|███▏      | 13018/40336 [00:53<01:48, 252.08it/s]

Leyendo pacientes:  32%|███▏      | 13046/40336 [00:53<01:45, 259.13it/s]

Leyendo pacientes:  32%|███▏      | 13073/40336 [00:53<01:45, 259.39it/s]

Leyendo pacientes:  32%|███▏      | 13102/40336 [00:53<01:43, 263.41it/s]

Leyendo pacientes:  33%|███▎      | 13133/40336 [00:53<01:39, 274.46it/s]

Leyendo pacientes:  33%|███▎      | 13161/40336 [00:53<01:38, 275.95it/s]

Leyendo pacientes:  33%|███▎      | 13189/40336 [00:53<01:39, 272.44it/s]

Leyendo pacientes:  33%|███▎      | 13218/40336 [00:54<01:39, 272.30it/s]

Leyendo pacientes:  33%|███▎      | 13246/40336 [00:54<01:40, 268.77it/s]

Leyendo pacientes:  33%|███▎      | 13273/40336 [00:54<01:41, 265.44it/s]

Leyendo pacientes:  33%|███▎      | 13301/40336 [00:54<01:40, 268.41it/s]

Leyendo pacientes:  33%|███▎      | 13329/40336 [00:54<01:40, 268.70it/s]

Leyendo pacientes:  33%|███▎      | 13356/40336 [00:54<01:41, 264.71it/s]

Leyendo pacientes:  33%|███▎      | 13385/40336 [00:54<01:39, 270.04it/s]

Leyendo pacientes:  33%|███▎      | 13414/40336 [00:54<01:37, 275.78it/s]

Leyendo pacientes:  33%|███▎      | 13442/40336 [00:54<01:37, 275.57it/s]

Leyendo pacientes:  33%|███▎      | 13470/40336 [00:54<01:38, 272.28it/s]

Leyendo pacientes:  33%|███▎      | 13498/40336 [00:55<01:40, 268.31it/s]

Leyendo pacientes:  34%|███▎      | 13529/40336 [00:55<01:37, 274.30it/s]

Leyendo pacientes:  34%|███▎      | 13558/40336 [00:55<01:36, 278.43it/s]

Leyendo pacientes:  34%|███▎      | 13586/40336 [00:55<01:36, 277.95it/s]

Leyendo pacientes:  34%|███▍      | 13616/40336 [00:55<01:36, 277.42it/s]

Leyendo pacientes:  34%|███▍      | 13646/40336 [00:55<01:35, 278.72it/s]

Leyendo pacientes:  34%|███▍      | 13674/40336 [00:55<01:36, 275.51it/s]

Leyendo pacientes:  34%|███▍      | 13705/40336 [00:55<01:33, 284.90it/s]

Leyendo pacientes:  34%|███▍      | 13739/40336 [00:55<01:30, 294.89it/s]

Leyendo pacientes:  34%|███▍      | 13769/40336 [00:56<01:31, 289.08it/s]

Leyendo pacientes:  34%|███▍      | 13798/40336 [00:56<01:33, 282.65it/s]

Leyendo pacientes:  34%|███▍      | 13827/40336 [00:56<01:34, 280.65it/s]

Leyendo pacientes:  34%|███▍      | 13856/40336 [00:56<01:38, 267.54it/s]

Leyendo pacientes:  34%|███▍      | 13883/40336 [00:56<01:44, 252.33it/s]

Leyendo pacientes:  34%|███▍      | 13909/40336 [00:56<01:46, 248.50it/s]

Leyendo pacientes:  35%|███▍      | 13935/40336 [00:56<01:46, 247.96it/s]

Leyendo pacientes:  35%|███▍      | 13963/40336 [00:56<01:43, 253.94it/s]

Leyendo pacientes:  35%|███▍      | 13989/40336 [00:56<01:47, 245.79it/s]

Leyendo pacientes:  35%|███▍      | 14015/40336 [00:57<01:47, 245.84it/s]

Leyendo pacientes:  35%|███▍      | 14040/40336 [00:57<01:48, 242.76it/s]

Leyendo pacientes:  35%|███▍      | 14067/40336 [00:57<01:45, 248.15it/s]

Leyendo pacientes:  35%|███▍      | 14098/40336 [00:57<01:39, 264.56it/s]

Leyendo pacientes:  35%|███▌      | 14127/40336 [00:57<01:37, 269.97it/s]

Leyendo pacientes:  35%|███▌      | 14157/40336 [00:57<01:35, 275.15it/s]

Leyendo pacientes:  35%|███▌      | 14186/40336 [00:57<01:34, 275.86it/s]

Leyendo pacientes:  35%|███▌      | 14214/40336 [00:57<01:35, 272.20it/s]

Leyendo pacientes:  35%|███▌      | 14242/40336 [00:57<01:39, 263.58it/s]

Leyendo pacientes:  35%|███▌      | 14270/40336 [00:57<01:37, 266.87it/s]

Leyendo pacientes:  35%|███▌      | 14298/40336 [00:58<01:37, 268.14it/s]

Leyendo pacientes:  36%|███▌      | 14327/40336 [00:58<01:35, 271.53it/s]

Leyendo pacientes:  36%|███▌      | 14356/40336 [00:58<01:35, 271.50it/s]

Leyendo pacientes:  36%|███▌      | 14384/40336 [00:58<01:35, 271.02it/s]

Leyendo pacientes:  36%|███▌      | 14413/40336 [00:58<01:34, 273.80it/s]

Leyendo pacientes:  36%|███▌      | 14441/40336 [00:58<01:37, 266.80it/s]

Leyendo pacientes:  36%|███▌      | 14469/40336 [00:58<01:36, 269.29it/s]

Leyendo pacientes:  36%|███▌      | 14498/40336 [00:58<01:34, 274.29it/s]

Leyendo pacientes:  36%|███▌      | 14526/40336 [00:58<01:33, 274.99it/s]

Leyendo pacientes:  36%|███▌      | 14554/40336 [00:59<01:35, 269.42it/s]

Leyendo pacientes:  36%|███▌      | 14581/40336 [00:59<01:35, 268.34it/s]

Leyendo pacientes:  36%|███▌      | 14610/40336 [00:59<01:33, 273.97it/s]

Leyendo pacientes:  36%|███▋      | 14638/40336 [00:59<01:33, 274.57it/s]

Leyendo pacientes:  36%|███▋      | 14666/40336 [00:59<01:33, 276.02it/s]

Leyendo pacientes:  36%|███▋      | 14694/40336 [00:59<01:32, 276.78it/s]

Leyendo pacientes:  36%|███▋      | 14722/40336 [00:59<01:32, 276.80it/s]

Leyendo pacientes:  37%|███▋      | 14750/40336 [00:59<01:32, 277.16it/s]

Leyendo pacientes:  37%|███▋      | 14778/40336 [00:59<01:32, 277.33it/s]

Leyendo pacientes:  37%|███▋      | 14806/40336 [00:59<01:32, 276.46it/s]

Leyendo pacientes:  37%|███▋      | 14834/40336 [01:00<01:34, 269.30it/s]

Leyendo pacientes:  37%|███▋      | 14862/40336 [01:00<01:33, 271.30it/s]

Leyendo pacientes:  37%|███▋      | 14890/40336 [01:00<01:34, 268.76it/s]

Leyendo pacientes:  37%|███▋      | 14917/40336 [01:00<01:34, 268.29it/s]

Leyendo pacientes:  37%|███▋      | 14945/40336 [01:00<01:33, 270.97it/s]

Leyendo pacientes:  37%|███▋      | 14973/40336 [01:00<01:33, 271.21it/s]

Leyendo pacientes:  37%|███▋      | 15001/40336 [01:00<01:33, 270.30it/s]

Leyendo pacientes:  37%|███▋      | 15029/40336 [01:00<01:33, 271.18it/s]

Leyendo pacientes:  37%|███▋      | 15059/40336 [01:00<01:30, 278.55it/s]

Leyendo pacientes:  37%|███▋      | 15087/40336 [01:02<08:29, 49.56it/s]

Leyendo pacientes:  37%|███▋      | 15115/40336 [01:02<06:25, 65.49it/s]

Leyendo pacientes:  38%|███▊      | 15143/40336 [01:02<04:57, 84.58it/s]

Leyendo pacientes:  38%|███▊      | 15174/40336 [01:02<03:49, 109.64it/s]

Leyendo pacientes:  38%|███▊      | 15205/40336 [01:02<03:05, 135.82it/s]

Leyendo pacientes:  38%|███▊      | 15232/40336 [01:03<02:39, 157.21it/s]

Leyendo pacientes:  38%|███▊      | 15259/40336 [01:03<02:20, 178.17it/s]

Leyendo pacientes:  38%|███▊      | 15286/40336 [01:03<02:08, 194.99it/s]

Leyendo pacientes:  38%|███▊      | 15313/40336 [01:03<02:00, 207.18it/s]

Leyendo pacientes:  38%|███▊      | 15342/40336 [01:03<01:50, 225.77it/s]

Leyendo pacientes:  38%|███▊      | 15370/40336 [01:03<01:44, 237.89it/s]

Leyendo pacientes:  38%|███▊      | 15397/40336 [01:03<01:41, 244.59it/s]

Leyendo pacientes:  38%|███▊      | 15427/40336 [01:03<01:36, 259.38it/s]

Leyendo pacientes:  38%|███▊      | 15460/40336 [01:03<01:30, 273.60it/s]

Leyendo pacientes:  38%|███▊      | 15490/40336 [01:03<01:28, 280.74it/s]

Leyendo pacientes:  38%|███▊      | 15519/40336 [01:04<01:28, 279.61it/s]

Leyendo pacientes:  39%|███▊      | 15548/40336 [01:04<01:28, 280.51it/s]

Leyendo pacientes:  39%|███▊      | 15577/40336 [01:04<01:27, 282.73it/s]

Leyendo pacientes:  39%|███▊      | 15606/40336 [01:04<01:28, 279.72it/s]

Leyendo pacientes:  39%|███▉      | 15635/40336 [01:04<01:28, 278.46it/s]

Leyendo pacientes:  39%|███▉      | 15663/40336 [01:04<01:31, 268.72it/s]

Leyendo pacientes:  39%|███▉      | 15691/40336 [01:04<01:30, 270.83it/s]

Leyendo pacientes:  39%|███▉      | 15722/40336 [01:04<01:29, 275.97it/s]

Leyendo pacientes:  39%|███▉      | 15752/40336 [01:04<01:27, 281.22it/s]

Leyendo pacientes:  39%|███▉      | 15781/40336 [01:05<01:28, 277.14it/s]

Leyendo pacientes:  39%|███▉      | 15811/40336 [01:05<01:27, 281.30it/s]

Leyendo pacientes:  39%|███▉      | 15840/40336 [01:05<01:27, 278.39it/s]

Leyendo pacientes:  39%|███▉      | 15869/40336 [01:05<01:28, 276.89it/s]

Leyendo pacientes:  39%|███▉      | 15900/40336 [01:05<01:27, 280.07it/s]

Leyendo pacientes:  39%|███▉      | 15929/40336 [01:05<01:27, 279.50it/s]

Leyendo pacientes:  40%|███▉      | 15957/40336 [01:05<01:27, 279.11it/s]

Leyendo pacientes:  40%|███▉      | 15986/40336 [01:05<01:26, 282.03it/s]

Leyendo pacientes:  40%|███▉      | 16015/40336 [01:05<01:27, 278.84it/s]

Leyendo pacientes:  40%|███▉      | 16043/40336 [01:05<01:27, 276.78it/s]

Leyendo pacientes:  40%|███▉      | 16071/40336 [01:06<01:31, 265.75it/s]

Leyendo pacientes:  40%|███▉      | 16099/40336 [01:06<01:31, 264.89it/s]

Leyendo pacientes:  40%|███▉      | 16129/40336 [01:06<01:28, 272.69it/s]

Leyendo pacientes:  40%|████      | 16158/40336 [01:06<01:27, 274.92it/s]

Leyendo pacientes:  40%|████      | 16187/40336 [01:06<01:27, 277.05it/s]

Leyendo pacientes:  40%|████      | 16215/40336 [01:06<01:28, 272.06it/s]

Leyendo pacientes:  40%|████      | 16243/40336 [01:06<01:27, 274.22it/s]

Leyendo pacientes:  40%|████      | 16271/40336 [01:06<01:28, 273.38it/s]

Leyendo pacientes:  40%|████      | 16302/40336 [01:06<01:26, 278.33it/s]

Leyendo pacientes:  40%|████      | 16330/40336 [01:07<01:26, 278.47it/s]

Leyendo pacientes:  41%|████      | 16358/40336 [01:07<01:27, 275.51it/s]

Leyendo pacientes:  41%|████      | 16389/40336 [01:07<01:25, 279.06it/s]

Leyendo pacientes:  41%|████      | 16419/40336 [01:07<01:24, 282.33it/s]

Leyendo pacientes:  41%|████      | 16448/40336 [01:07<01:24, 282.51it/s]

Leyendo pacientes:  41%|████      | 16477/40336 [01:07<01:26, 277.07it/s]

Leyendo pacientes:  41%|████      | 16505/40336 [01:07<01:25, 277.91it/s]

Leyendo pacientes:  41%|████      | 16534/40336 [01:07<01:25, 278.80it/s]

Leyendo pacientes:  41%|████      | 16562/40336 [01:07<01:25, 277.50it/s]

Leyendo pacientes:  41%|████      | 16591/40336 [01:07<01:24, 279.57it/s]

Leyendo pacientes:  41%|████      | 16620/40336 [01:08<01:25, 278.21it/s]

Leyendo pacientes:  41%|████▏     | 16649/40336 [01:08<01:25, 276.34it/s]

Leyendo pacientes:  41%|████▏     | 16678/40336 [01:08<01:25, 278.11it/s]

Leyendo pacientes:  41%|████▏     | 16706/40336 [01:08<01:26, 272.97it/s]

Leyendo pacientes:  41%|████▏     | 16736/40336 [01:08<01:24, 278.84it/s]

Leyendo pacientes:  42%|████▏     | 16764/40336 [01:08<01:25, 274.81it/s]

Leyendo pacientes:  42%|████▏     | 16792/40336 [01:08<01:26, 271.86it/s]

Leyendo pacientes:  42%|████▏     | 16820/40336 [01:08<01:31, 256.30it/s]

Leyendo pacientes:  42%|████▏     | 16850/40336 [01:08<01:29, 263.36it/s]

Leyendo pacientes:  42%|████▏     | 16878/40336 [01:09<01:27, 267.76it/s]

Leyendo pacientes:  42%|████▏     | 16906/40336 [01:09<01:27, 268.16it/s]

Leyendo pacientes:  42%|████▏     | 16933/40336 [01:09<01:28, 263.67it/s]

Leyendo pacientes:  42%|████▏     | 16963/40336 [01:09<01:26, 270.58it/s]

Leyendo pacientes:  42%|████▏     | 16992/40336 [01:09<01:26, 269.48it/s]

Leyendo pacientes:  42%|████▏     | 17020/40336 [01:09<01:26, 268.92it/s]

Leyendo pacientes:  42%|████▏     | 17047/40336 [01:09<01:26, 268.69it/s]

Leyendo pacientes:  42%|████▏     | 17075/40336 [01:09<01:27, 266.52it/s]

Leyendo pacientes:  42%|████▏     | 17103/40336 [01:09<01:26, 268.73it/s]

Leyendo pacientes:  42%|████▏     | 17132/40336 [01:09<01:25, 272.79it/s]

Leyendo pacientes:  43%|████▎     | 17160/40336 [01:10<01:24, 274.58it/s]

Leyendo pacientes:  43%|████▎     | 17189/40336 [01:10<01:24, 273.71it/s]

Leyendo pacientes:  43%|████▎     | 17217/40336 [01:10<01:25, 269.92it/s]

Leyendo pacientes:  43%|████▎     | 17246/40336 [01:10<01:25, 271.00it/s]

Leyendo pacientes:  43%|████▎     | 17279/40336 [01:10<01:21, 282.49it/s]

Leyendo pacientes:  43%|████▎     | 17309/40336 [01:10<01:21, 281.51it/s]

Leyendo pacientes:  43%|████▎     | 17338/40336 [01:10<01:23, 276.96it/s]

Leyendo pacientes:  43%|████▎     | 17368/40336 [01:10<01:22, 279.36it/s]

Leyendo pacientes:  43%|████▎     | 17397/40336 [01:10<01:21, 280.43it/s]

Leyendo pacientes:  43%|████▎     | 17426/40336 [01:11<01:22, 276.78it/s]

Leyendo pacientes:  43%|████▎     | 17454/40336 [01:11<01:24, 272.07it/s]

Leyendo pacientes:  43%|████▎     | 17482/40336 [01:11<01:23, 272.79it/s]

Leyendo pacientes:  43%|████▎     | 17510/40336 [01:11<01:23, 273.92it/s]

Leyendo pacientes:  43%|████▎     | 17539/40336 [01:11<01:22, 274.79it/s]

Leyendo pacientes:  44%|████▎     | 17567/40336 [01:11<01:22, 276.20it/s]

Leyendo pacientes:  44%|████▎     | 17595/40336 [01:11<01:23, 271.35it/s]

Leyendo pacientes:  44%|████▎     | 17623/40336 [01:11<01:23, 273.15it/s]

Leyendo pacientes:  44%|████▍     | 17651/40336 [01:11<01:22, 273.66it/s]

Leyendo pacientes:  44%|████▍     | 17682/40336 [01:11<01:21, 276.59it/s]

Leyendo pacientes:  44%|████▍     | 17710/40336 [01:12<01:23, 270.93it/s]

Leyendo pacientes:  44%|████▍     | 17738/40336 [01:12<01:23, 270.37it/s]

Leyendo pacientes:  44%|████▍     | 17768/40336 [01:12<01:22, 272.92it/s]

Leyendo pacientes:  44%|████▍     | 17799/40336 [01:12<01:21, 277.86it/s]

Leyendo pacientes:  44%|████▍     | 17828/40336 [01:12<01:21, 275.16it/s]

Leyendo pacientes:  44%|████▍     | 17856/40336 [01:12<01:22, 273.04it/s]

Leyendo pacientes:  44%|████▍     | 17884/40336 [01:12<01:23, 269.68it/s]

Leyendo pacientes:  44%|████▍     | 17913/40336 [01:12<01:22, 272.30it/s]

Leyendo pacientes:  44%|████▍     | 17944/40336 [01:12<01:19, 280.93it/s]

Leyendo pacientes:  45%|████▍     | 17976/40336 [01:13<01:17, 288.58it/s]

Leyendo pacientes:  45%|████▍     | 18005/40336 [01:13<01:17, 287.69it/s]

Leyendo pacientes:  45%|████▍     | 18034/40336 [01:13<01:19, 281.92it/s]

Leyendo pacientes:  45%|████▍     | 18063/40336 [01:13<01:19, 280.78it/s]

Leyendo pacientes:  45%|████▍     | 18092/40336 [01:13<01:19, 278.63it/s]

Leyendo pacientes:  45%|████▍     | 18121/40336 [01:13<01:19, 278.02it/s]

Leyendo pacientes:  45%|████▍     | 18149/40336 [01:13<01:19, 277.90it/s]

Leyendo pacientes:  45%|████▌     | 18177/40336 [01:13<01:20, 276.67it/s]

Leyendo pacientes:  45%|████▌     | 18205/40336 [01:13<01:21, 272.89it/s]

Leyendo pacientes:  45%|████▌     | 18235/40336 [01:13<01:20, 275.65it/s]

Leyendo pacientes:  45%|████▌     | 18263/40336 [01:14<01:21, 270.13it/s]

Leyendo pacientes:  45%|████▌     | 18291/40336 [01:14<01:21, 269.10it/s]

Leyendo pacientes:  45%|████▌     | 18320/40336 [01:14<01:21, 269.55it/s]

Leyendo pacientes:  45%|████▌     | 18348/40336 [01:14<01:21, 271.23it/s]

Leyendo pacientes:  46%|████▌     | 18376/40336 [01:14<01:20, 273.74it/s]

Leyendo pacientes:  46%|████▌     | 18404/40336 [01:14<01:21, 270.72it/s]

Leyendo pacientes:  46%|████▌     | 18433/40336 [01:14<01:19, 274.36it/s]

Leyendo pacientes:  46%|████▌     | 18461/40336 [01:14<01:20, 270.23it/s]

Leyendo pacientes:  46%|████▌     | 18489/40336 [01:14<01:20, 271.09it/s]

Leyendo pacientes:  46%|████▌     | 18517/40336 [01:14<01:20, 269.87it/s]

Leyendo pacientes:  46%|████▌     | 18544/40336 [01:15<01:21, 268.09it/s]

Leyendo pacientes:  46%|████▌     | 18574/40336 [01:15<01:18, 276.51it/s]

Leyendo pacientes:  46%|████▌     | 18604/40336 [01:15<01:17, 280.14it/s]

Leyendo pacientes:  46%|████▌     | 18633/40336 [01:15<01:16, 282.56it/s]

Leyendo pacientes:  46%|████▋     | 18662/40336 [01:15<01:19, 273.52it/s]

Leyendo pacientes:  46%|████▋     | 18690/40336 [01:15<01:20, 269.81it/s]

Leyendo pacientes:  46%|████▋     | 18719/40336 [01:15<01:19, 271.81it/s]

Leyendo pacientes:  46%|████▋     | 18749/40336 [01:15<01:17, 277.31it/s]

Leyendo pacientes:  47%|████▋     | 18778/40336 [01:15<01:18, 274.67it/s]

Leyendo pacientes:  47%|████▋     | 18807/40336 [01:16<01:18, 273.82it/s]

Leyendo pacientes:  47%|████▋     | 18835/40336 [01:16<01:18, 274.14it/s]

Leyendo pacientes:  47%|████▋     | 18863/40336 [01:16<01:18, 274.09it/s]

Leyendo pacientes:  47%|████▋     | 18891/40336 [01:16<01:17, 275.41it/s]

Leyendo pacientes:  47%|████▋     | 18920/40336 [01:16<01:17, 275.40it/s]

Leyendo pacientes:  47%|████▋     | 18948/40336 [01:16<01:17, 275.60it/s]

Leyendo pacientes:  47%|████▋     | 18977/40336 [01:16<01:17, 276.10it/s]

Leyendo pacientes:  47%|████▋     | 19005/40336 [01:16<01:18, 272.49it/s]

Leyendo pacientes:  47%|████▋     | 19033/40336 [01:16<01:18, 271.87it/s]

Leyendo pacientes:  47%|████▋     | 19061/40336 [01:16<01:19, 268.83it/s]

Leyendo pacientes:  47%|████▋     | 19088/40336 [01:17<01:19, 268.64it/s]

Leyendo pacientes:  47%|████▋     | 19115/40336 [01:17<01:19, 268.30it/s]

Leyendo pacientes:  47%|████▋     | 19142/40336 [01:17<01:19, 267.15it/s]

Leyendo pacientes:  48%|████▊     | 19169/40336 [01:19<08:26, 41.77it/s]

Leyendo pacientes:  48%|████▊     | 19197/40336 [01:19<06:15, 56.30it/s]

Leyendo pacientes:  48%|████▊     | 19224/40336 [01:19<04:47, 73.44it/s]

Leyendo pacientes:  48%|████▊     | 19253/40336 [01:19<03:40, 95.45it/s]

Leyendo pacientes:  48%|████▊     | 19281/40336 [01:19<02:58, 117.86it/s]

Leyendo pacientes:  48%|████▊     | 19310/40336 [01:19<02:26, 143.44it/s]

Leyendo pacientes:  48%|████▊     | 19340/40336 [01:19<02:03, 169.40it/s]

Leyendo pacientes:  48%|████▊     | 19371/40336 [01:19<01:47, 195.27it/s]

Leyendo pacientes:  48%|████▊     | 19399/40336 [01:20<01:39, 210.76it/s]

Leyendo pacientes:  48%|████▊     | 19429/40336 [01:20<01:31, 228.28it/s]

Leyendo pacientes:  48%|████▊     | 19457/40336 [01:20<01:27, 238.08it/s]

Leyendo pacientes:  48%|████▊     | 19485/40336 [01:20<01:26, 241.10it/s]

Leyendo pacientes:  48%|████▊     | 19512/40336 [01:20<01:30, 229.55it/s]

Leyendo pacientes:  48%|████▊     | 19541/40336 [01:20<01:25, 244.55it/s]

Leyendo pacientes:  49%|████▊     | 19571/40336 [01:20<01:20, 259.48it/s]

Leyendo pacientes:  49%|████▊     | 19602/40336 [01:20<01:16, 272.64it/s]

Leyendo pacientes:  49%|████▊     | 19631/40336 [01:20<01:14, 276.78it/s]

Leyendo pacientes:  49%|████▊     | 19660/40336 [01:21<01:14, 277.84it/s]

Leyendo pacientes:  49%|████▉     | 19689/40336 [01:21<01:15, 275.10it/s]

Leyendo pacientes:  49%|████▉     | 19717/40336 [01:21<01:14, 275.64it/s]

Leyendo pacientes:  49%|████▉     | 19745/40336 [01:21<01:15, 273.90it/s]

Leyendo pacientes:  49%|████▉     | 19774/40336 [01:21<01:14, 275.51it/s]

Leyendo pacientes:  49%|████▉     | 19802/40336 [01:21<01:15, 273.61it/s]

Leyendo pacientes:  49%|████▉     | 19830/40336 [01:21<01:17, 265.24it/s]

Leyendo pacientes:  49%|████▉     | 19858/40336 [01:21<01:16, 268.81it/s]

Leyendo pacientes:  49%|████▉     | 19885/40336 [01:21<01:18, 260.07it/s]

Leyendo pacientes:  49%|████▉     | 19912/40336 [01:21<01:18, 261.53it/s]

Leyendo pacientes:  49%|████▉     | 19941/40336 [01:22<01:17, 264.37it/s]

Leyendo pacientes:  50%|████▉     | 19972/40336 [01:22<01:14, 272.03it/s]

Leyendo pacientes:  50%|████▉     | 20002/40336 [01:22<01:13, 276.43it/s]

Leyendo pacientes:  50%|████▉     | 20031/40336 [01:22<01:13, 276.21it/s]

Leyendo pacientes:  50%|████▉     | 20060/40336 [01:22<01:12, 278.86it/s]

Leyendo pacientes:  50%|████▉     | 20088/40336 [01:22<01:13, 274.47it/s]

Leyendo pacientes:  50%|████▉     | 20116/40336 [01:22<01:17, 259.91it/s]

Leyendo pacientes:  50%|████▉     | 20144/40336 [01:22<01:16, 263.80it/s]

Leyendo pacientes:  50%|█████     | 20177/40336 [01:22<01:11, 280.35it/s]

Leyendo pacientes:  50%|█████     | 20206/40336 [01:23<01:12, 276.82it/s]

Leyendo pacientes:  50%|█████     | 20239/40336 [01:23<01:09, 288.27it/s]

Leyendo pacientes:  50%|█████     | 20272/40336 [01:23<01:06, 300.14it/s]

Leyendo pacientes:  50%|█████     | 20305/40336 [01:23<01:05, 306.49it/s]

Leyendo pacientes:  50%|█████     | 20336/40336 [01:23<01:05, 305.66it/s]

Leyendo pacientes:  50%|█████     | 20367/40336 [01:23<01:06, 302.26it/s]

Leyendo pacientes:  51%|█████     | 20398/40336 [01:23<01:05, 304.00it/s]

Leyendo pacientes:  51%|█████     | 20432/40336 [01:23<01:03, 313.95it/s]

Leyendo pacientes:  51%|█████     | 20464/40336 [01:23<01:03, 313.58it/s]

Leyendo pacientes:  51%|█████     | 20496/40336 [01:23<01:03, 314.29it/s]

Leyendo pacientes:  51%|█████     | 20528/40336 [01:24<01:05, 302.63it/s]

Leyendo pacientes:  51%|█████     | 20559/40336 [01:24<01:11, 277.13it/s]

Leyendo pacientes:  51%|█████     | 20588/40336 [01:24<01:14, 264.18it/s]

Leyendo pacientes:  51%|█████     | 20615/40336 [01:24<01:14, 265.32it/s]

Leyendo pacientes:  51%|█████     | 20642/40336 [01:24<01:16, 257.39it/s]

Leyendo pacientes:  51%|█████     | 20669/40336 [01:24<01:15, 259.42it/s]

Leyendo pacientes:  51%|█████▏    | 20699/40336 [01:24<01:12, 269.81it/s]

Leyendo pacientes:  51%|█████▏    | 20727/40336 [01:24<01:12, 269.55it/s]

Leyendo pacientes:  51%|█████▏    | 20756/40336 [01:24<01:12, 271.65it/s]

Leyendo pacientes:  52%|█████▏    | 20784/40336 [01:25<01:18, 248.28it/s]

Leyendo pacientes:  52%|█████▏    | 20811/40336 [01:25<01:17, 252.97it/s]

Leyendo pacientes:  52%|█████▏    | 20837/40336 [01:25<01:17, 253.08it/s]

Leyendo pacientes:  52%|█████▏    | 20863/40336 [01:25<01:19, 244.31it/s]

Leyendo pacientes:  52%|█████▏    | 20889/40336 [01:25<01:19, 245.89it/s]

Leyendo pacientes:  52%|█████▏    | 20915/40336 [01:25<01:18, 248.44it/s]

Leyendo pacientes:  52%|█████▏    | 20940/40336 [01:25<01:21, 237.96it/s]

Leyendo pacientes:  52%|█████▏    | 20967/40336 [01:25<01:19, 243.71it/s]

Leyendo pacientes:  52%|█████▏    | 20993/40336 [01:25<01:18, 247.82it/s]

Leyendo pacientes:  52%|█████▏    | 21018/40336 [01:26<01:18, 246.65it/s]

Leyendo pacientes:  52%|█████▏    | 21043/40336 [01:26<01:20, 240.91it/s]

Leyendo pacientes:  52%|█████▏    | 21073/40336 [01:26<01:15, 255.25it/s]

Leyendo pacientes:  52%|█████▏    | 21103/40336 [01:26<01:13, 263.06it/s]

Leyendo pacientes:  52%|█████▏    | 21133/40336 [01:26<01:11, 268.60it/s]

Leyendo pacientes:  52%|█████▏    | 21160/40336 [01:26<01:13, 262.58it/s]

Leyendo pacientes:  53%|█████▎    | 21188/40336 [01:26<01:11, 266.27it/s]

Leyendo pacientes:  53%|█████▎    | 21217/40336 [01:26<01:10, 270.99it/s]

Leyendo pacientes:  53%|█████▎    | 21245/40336 [01:26<01:10, 271.47it/s]

Leyendo pacientes:  53%|█████▎    | 21273/40336 [01:26<01:11, 268.12it/s]

Leyendo pacientes:  53%|█████▎    | 21300/40336 [01:27<01:19, 240.44it/s]

Leyendo pacientes:  53%|█████▎    | 21326/40336 [01:27<01:17, 243.86it/s]

Leyendo pacientes:  53%|█████▎    | 21357/40336 [01:27<01:13, 258.33it/s]

Leyendo pacientes:  53%|█████▎    | 21387/40336 [01:27<01:11, 264.02it/s]

Leyendo pacientes:  53%|█████▎    | 21415/40336 [01:27<01:11, 264.99it/s]

Leyendo pacientes:  53%|█████▎    | 21442/40336 [01:27<01:13, 256.08it/s]

Leyendo pacientes:  53%|█████▎    | 21469/40336 [01:27<01:12, 258.64it/s]

Leyendo pacientes:  53%|█████▎    | 21496/40336 [01:27<01:12, 258.82it/s]

Leyendo pacientes:  53%|█████▎    | 21524/40336 [01:27<01:11, 263.17it/s]

Leyendo pacientes:  53%|█████▎    | 21553/40336 [01:28<01:09, 269.22it/s]

Leyendo pacientes:  54%|█████▎    | 21581/40336 [01:28<01:09, 270.11it/s]

Leyendo pacientes:  54%|█████▎    | 21609/40336 [01:28<01:09, 270.40it/s]

Leyendo pacientes:  54%|█████▎    | 21637/40336 [01:28<01:08, 272.07it/s]

Leyendo pacientes:  54%|█████▎    | 21666/40336 [01:28<01:07, 275.20it/s]

Leyendo pacientes:  54%|█████▍    | 21694/40336 [01:28<01:08, 273.58it/s]

Leyendo pacientes:  54%|█████▍    | 21724/40336 [01:28<01:07, 275.33it/s]

Leyendo pacientes:  54%|█████▍    | 21752/40336 [01:28<01:08, 272.14it/s]

Leyendo pacientes:  54%|█████▍    | 21781/40336 [01:28<01:07, 276.93it/s]

Leyendo pacientes:  54%|█████▍    | 21812/40336 [01:29<01:05, 281.39it/s]

Leyendo pacientes:  54%|█████▍    | 21841/40336 [01:29<01:06, 278.99it/s]

Leyendo pacientes:  54%|█████▍    | 21869/40336 [01:29<01:10, 263.65it/s]

Leyendo pacientes:  54%|█████▍    | 21896/40336 [01:29<01:11, 256.86it/s]

Leyendo pacientes:  54%|█████▍    | 21924/40336 [01:29<01:10, 260.24it/s]

Leyendo pacientes:  54%|█████▍    | 21951/40336 [01:29<01:12, 253.87it/s]

Leyendo pacientes:  54%|█████▍    | 21977/40336 [01:29<01:13, 250.87it/s]

Leyendo pacientes:  55%|█████▍    | 22003/40336 [01:29<01:14, 247.18it/s]

Leyendo pacientes:  55%|█████▍    | 22028/40336 [01:29<01:14, 244.38it/s]

Leyendo pacientes:  55%|█████▍    | 22053/40336 [01:29<01:15, 242.47it/s]

Leyendo pacientes:  55%|█████▍    | 22078/40336 [01:30<01:18, 232.22it/s]

Leyendo pacientes:  55%|█████▍    | 22104/40336 [01:30<01:16, 238.50it/s]

Leyendo pacientes:  55%|█████▍    | 22130/40336 [01:30<01:14, 243.68it/s]

Leyendo pacientes:  55%|█████▍    | 22155/40336 [01:30<01:17, 233.43it/s]

Leyendo pacientes:  55%|█████▍    | 22181/40336 [01:30<01:16, 237.79it/s]

Leyendo pacientes:  55%|█████▌    | 22206/40336 [01:30<01:15, 239.55it/s]

Leyendo pacientes:  55%|█████▌    | 22231/40336 [01:30<01:15, 238.75it/s]

Leyendo pacientes:  55%|█████▌    | 22257/40336 [01:30<01:14, 243.80it/s]

Leyendo pacientes:  55%|█████▌    | 22282/40336 [01:30<01:13, 244.26it/s]

Leyendo pacientes:  55%|█████▌    | 22308/40336 [01:31<01:12, 248.46it/s]

Leyendo pacientes:  55%|█████▌    | 22333/40336 [01:31<01:15, 239.83it/s]

Leyendo pacientes:  55%|█████▌    | 22358/40336 [01:31<01:16, 235.47it/s]

Leyendo pacientes:  56%|█████▌    | 22387/40336 [01:31<01:13, 244.83it/s]

Leyendo pacientes:  56%|█████▌    | 22415/40336 [01:31<01:10, 254.17it/s]

Leyendo pacientes:  56%|█████▌    | 22441/40336 [01:31<01:15, 237.17it/s]

Leyendo pacientes:  56%|█████▌    | 22465/40336 [01:31<01:18, 228.12it/s]

Leyendo pacientes:  56%|█████▌    | 22489/40336 [01:31<01:21, 218.71it/s]

Leyendo pacientes:  56%|█████▌    | 22518/40336 [01:31<01:16, 232.43it/s]

Leyendo pacientes:  56%|█████▌    | 22546/40336 [01:32<01:12, 245.38it/s]

Leyendo pacientes:  56%|█████▌    | 22571/40336 [01:32<01:13, 240.09it/s]

Leyendo pacientes:  56%|█████▌    | 22597/40336 [01:32<01:13, 241.67it/s]

Leyendo pacientes:  56%|█████▌    | 22622/40336 [01:32<01:13, 239.90it/s]

Leyendo pacientes:  56%|█████▌    | 22650/40336 [01:32<01:11, 247.20it/s]

Leyendo pacientes:  56%|█████▌    | 22678/40336 [01:32<01:10, 251.34it/s]

Leyendo pacientes:  56%|█████▋    | 22705/40336 [01:32<01:10, 251.51it/s]

Leyendo pacientes:  56%|█████▋    | 22732/40336 [01:32<01:09, 252.57it/s]

Leyendo pacientes:  56%|█████▋    | 22758/40336 [01:32<01:09, 253.04it/s]

Leyendo pacientes:  56%|█████▋    | 22784/40336 [01:33<01:11, 243.99it/s]

Leyendo pacientes:  57%|█████▋    | 22810/40336 [01:33<01:11, 246.63it/s]

Leyendo pacientes:  57%|█████▋    | 22837/40336 [01:33<01:09, 250.76it/s]

Leyendo pacientes:  57%|█████▋    | 22866/40336 [01:33<01:07, 257.03it/s]

Leyendo pacientes:  57%|█████▋    | 22894/40336 [01:33<01:07, 258.96it/s]

Leyendo pacientes:  57%|█████▋    | 22920/40336 [01:33<01:08, 255.31it/s]

Leyendo pacientes:  57%|█████▋    | 22946/40336 [01:33<01:12, 240.17it/s]

Leyendo pacientes:  57%|█████▋    | 22971/40336 [01:33<01:12, 239.58it/s]

Leyendo pacientes:  57%|█████▋    | 22998/40336 [01:33<01:10, 245.89it/s]

Leyendo pacientes:  57%|█████▋    | 23028/40336 [01:33<01:07, 256.10it/s]

Leyendo pacientes:  57%|█████▋    | 23056/40336 [01:34<01:06, 260.67it/s]

Leyendo pacientes:  57%|█████▋    | 23083/40336 [01:34<01:05, 262.07it/s]

Leyendo pacientes:  57%|█████▋    | 23111/40336 [01:34<01:04, 266.53it/s]

Leyendo pacientes:  57%|█████▋    | 23139/40336 [01:34<01:03, 270.38it/s]

Leyendo pacientes:  57%|█████▋    | 23168/40336 [01:34<01:02, 276.01it/s]

Leyendo pacientes:  58%|█████▊    | 23196/40336 [01:34<01:01, 276.84it/s]

Leyendo pacientes:  58%|█████▊    | 23224/40336 [01:34<01:01, 276.20it/s]

Leyendo pacientes:  58%|█████▊    | 23252/40336 [01:34<01:03, 270.27it/s]

Leyendo pacientes:  58%|█████▊    | 23280/40336 [01:34<01:03, 269.58it/s]

Leyendo pacientes:  58%|█████▊    | 23310/40336 [01:35<01:01, 276.71it/s]

Leyendo pacientes:  58%|█████▊    | 23339/40336 [01:35<01:01, 278.39it/s]

Leyendo pacientes:  58%|█████▊    | 23367/40336 [01:35<01:02, 271.20it/s]

Leyendo pacientes:  58%|█████▊    | 23395/40336 [01:35<01:04, 262.45it/s]

Leyendo pacientes:  58%|█████▊    | 23422/40336 [01:35<01:05, 259.62it/s]

Leyendo pacientes:  58%|█████▊    | 23449/40336 [01:35<01:05, 256.36it/s]

Leyendo pacientes:  58%|█████▊    | 23476/40336 [01:35<01:05, 255.82it/s]

Leyendo pacientes:  58%|█████▊    | 23502/40336 [01:35<01:05, 255.24it/s]

Leyendo pacientes:  58%|█████▊    | 23533/40336 [01:35<01:02, 266.91it/s]

Leyendo pacientes:  58%|█████▊    | 23562/40336 [01:35<01:01, 272.55it/s]

Leyendo pacientes:  58%|█████▊    | 23590/40336 [01:36<01:02, 270.06it/s]

Leyendo pacientes:  59%|█████▊    | 23618/40336 [01:36<01:03, 264.20it/s]

Leyendo pacientes:  59%|█████▊    | 23646/40336 [01:36<01:02, 266.75it/s]

Leyendo pacientes:  59%|█████▊    | 23676/40336 [01:36<01:00, 274.15it/s]

Leyendo pacientes:  59%|█████▉    | 23705/40336 [01:36<01:00, 273.49it/s]

Leyendo pacientes:  59%|█████▉    | 23733/40336 [01:36<01:01, 270.26it/s]

Leyendo pacientes:  59%|█████▉    | 23761/40336 [01:36<01:02, 267.01it/s]

Leyendo pacientes:  59%|█████▉    | 23788/40336 [01:36<01:02, 263.10it/s]

Leyendo pacientes:  59%|█████▉    | 23817/40336 [01:36<01:02, 264.73it/s]

Leyendo pacientes:  59%|█████▉    | 23846/40336 [01:37<01:01, 269.48it/s]

Leyendo pacientes:  59%|█████▉    | 23873/40336 [01:37<01:01, 265.64it/s]

Leyendo pacientes:  59%|█████▉    | 23900/40336 [01:37<01:01, 266.04it/s]

Leyendo pacientes:  59%|█████▉    | 23927/40336 [01:37<01:03, 256.48it/s]

Leyendo pacientes:  59%|█████▉    | 23956/40336 [01:37<01:02, 262.22it/s]

Leyendo pacientes:  59%|█████▉    | 23983/40336 [01:37<01:02, 259.59it/s]

Leyendo pacientes:  60%|█████▉    | 24010/40336 [01:37<01:03, 258.21it/s]

Leyendo pacientes:  60%|█████▉    | 24037/40336 [01:37<01:03, 256.15it/s]

Leyendo pacientes:  60%|█████▉    | 24064/40336 [01:37<01:02, 259.12it/s]

Leyendo pacientes:  60%|█████▉    | 24091/40336 [01:37<01:03, 257.70it/s]

Leyendo pacientes:  60%|█████▉    | 24118/40336 [01:38<01:03, 255.92it/s]

Leyendo pacientes:  60%|█████▉    | 24147/40336 [01:38<01:02, 259.48it/s]

Leyendo pacientes:  60%|█████▉    | 24175/40336 [01:38<01:01, 262.29it/s]

Leyendo pacientes:  60%|██████    | 24202/40336 [01:38<01:01, 263.21it/s]

Leyendo pacientes:  60%|██████    | 24229/40336 [01:40<06:58, 38.48it/s]

Leyendo pacientes:  60%|██████    | 24254/40336 [01:40<05:19, 50.40it/s]

Leyendo pacientes:  60%|██████    | 24283/40336 [01:40<03:55, 68.05it/s]

Leyendo pacientes:  60%|██████    | 24312/40336 [01:40<02:59, 89.09it/s]

Leyendo pacientes:  60%|██████    | 24338/40336 [01:40<02:25, 109.63it/s]

Leyendo pacientes:  60%|██████    | 24365/40336 [01:41<02:00, 133.06it/s]

Leyendo pacientes:  60%|██████    | 24393/40336 [01:41<01:41, 157.10it/s]

Leyendo pacientes:  61%|██████    | 24420/40336 [01:41<01:28, 179.21it/s]

Leyendo pacientes:  61%|██████    | 24447/40336 [01:41<01:19, 198.94it/s]

Leyendo pacientes:  61%|██████    | 24474/40336 [01:41<01:13, 215.66it/s]

Leyendo pacientes:  61%|██████    | 24502/40336 [01:41<01:09, 228.48it/s]

Leyendo pacientes:  61%|██████    | 24530/40336 [01:41<01:06, 238.11it/s]

Leyendo pacientes:  61%|██████    | 24558/40336 [01:41<01:03, 249.13it/s]

Leyendo pacientes:  61%|██████    | 24586/40336 [01:41<01:01, 255.41it/s]

Leyendo pacientes:  61%|██████    | 24615/40336 [01:41<00:59, 263.75it/s]

Leyendo pacientes:  61%|██████    | 24644/40336 [01:42<00:57, 270.55it/s]

Leyendo pacientes:  61%|██████    | 24672/40336 [01:42<00:58, 269.95it/s]

Leyendo pacientes:  61%|██████    | 24700/40336 [01:42<00:59, 264.45it/s]

Leyendo pacientes:  61%|██████▏   | 24727/40336 [01:42<00:59, 263.00it/s]

Leyendo pacientes:  61%|██████▏   | 24754/40336 [01:42<01:00, 259.33it/s]

Leyendo pacientes:  61%|██████▏   | 24781/40336 [01:42<00:59, 261.06it/s]

Leyendo pacientes:  62%|██████▏   | 24808/40336 [01:42<01:00, 258.58it/s]

Leyendo pacientes:  62%|██████▏   | 24834/40336 [01:42<00:59, 258.46it/s]

Leyendo pacientes:  62%|██████▏   | 24860/40336 [01:42<01:02, 249.38it/s]

Leyendo pacientes:  62%|██████▏   | 24886/40336 [01:43<01:02, 249.18it/s]

Leyendo pacientes:  62%|██████▏   | 24911/40336 [01:43<01:02, 247.74it/s]

Leyendo pacientes:  62%|██████▏   | 24936/40336 [01:43<01:04, 240.17it/s]

Leyendo pacientes:  62%|██████▏   | 24961/40336 [01:43<01:04, 238.59it/s]

Leyendo pacientes:  62%|██████▏   | 24986/40336 [01:43<01:04, 238.19it/s]

Leyendo pacientes:  62%|██████▏   | 25013/40336 [01:43<01:02, 245.46it/s]

Leyendo pacientes:  62%|██████▏   | 25039/40336 [01:43<01:01, 249.50it/s]

Leyendo pacientes:  62%|██████▏   | 25065/40336 [01:43<01:00, 252.54it/s]

Leyendo pacientes:  62%|██████▏   | 25091/40336 [01:43<01:00, 253.37it/s]

Leyendo pacientes:  62%|██████▏   | 25119/40336 [01:43<00:59, 256.02it/s]

Leyendo pacientes:  62%|██████▏   | 25145/40336 [01:44<01:00, 252.77it/s]

Leyendo pacientes:  62%|██████▏   | 25171/40336 [01:44<01:00, 249.02it/s]

Leyendo pacientes:  62%|██████▏   | 25198/40336 [01:44<01:00, 250.33it/s]

Leyendo pacientes:  63%|██████▎   | 25224/40336 [01:44<01:01, 243.77it/s]

Leyendo pacientes:  63%|██████▎   | 25251/40336 [01:44<01:00, 249.67it/s]

Leyendo pacientes:  63%|██████▎   | 25277/40336 [01:44<01:00, 250.54it/s]

Leyendo pacientes:  63%|██████▎   | 25304/40336 [01:44<00:59, 250.92it/s]

Leyendo pacientes:  63%|██████▎   | 25331/40336 [01:44<00:59, 251.65it/s]

Leyendo pacientes:  63%|██████▎   | 25358/40336 [01:44<00:59, 253.40it/s]

Leyendo pacientes:  63%|██████▎   | 25385/40336 [01:45<00:58, 257.27it/s]

Leyendo pacientes:  63%|██████▎   | 25411/40336 [01:45<00:59, 250.55it/s]

Leyendo pacientes:  63%|██████▎   | 25437/40336 [01:45<00:59, 250.24it/s]

Leyendo pacientes:  63%|██████▎   | 25465/40336 [01:45<00:58, 255.24it/s]

Leyendo pacientes:  63%|██████▎   | 25493/40336 [01:45<00:56, 261.40it/s]

Leyendo pacientes:  63%|██████▎   | 25521/40336 [01:45<00:56, 264.06it/s]

Leyendo pacientes:  63%|██████▎   | 25548/40336 [01:45<00:57, 256.54it/s]

Leyendo pacientes:  63%|██████▎   | 25574/40336 [01:45<00:58, 253.24it/s]

Leyendo pacientes:  63%|██████▎   | 25601/40336 [01:45<00:58, 252.14it/s]

Leyendo pacientes:  64%|██████▎   | 25630/40336 [01:45<00:56, 258.15it/s]

Leyendo pacientes:  64%|██████▎   | 25656/40336 [01:46<00:57, 253.88it/s]

Leyendo pacientes:  64%|██████▎   | 25683/40336 [01:46<00:57, 253.74it/s]

Leyendo pacientes:  64%|██████▎   | 25711/40336 [01:46<00:57, 256.27it/s]

Leyendo pacientes:  64%|██████▍   | 25738/40336 [01:46<00:56, 257.69it/s]

Leyendo pacientes:  64%|██████▍   | 25765/40336 [01:46<00:55, 260.24it/s]

Leyendo pacientes:  64%|██████▍   | 25792/40336 [01:46<00:55, 262.41it/s]

Leyendo pacientes:  64%|██████▍   | 25819/40336 [01:46<00:55, 260.57it/s]

Leyendo pacientes:  64%|██████▍   | 25846/40336 [01:46<00:56, 258.42it/s]

Leyendo pacientes:  64%|██████▍   | 25872/40336 [01:46<00:57, 253.23it/s]

Leyendo pacientes:  64%|██████▍   | 25898/40336 [01:47<00:57, 251.48it/s]

Leyendo pacientes:  64%|██████▍   | 25924/40336 [01:47<00:59, 244.01it/s]

Leyendo pacientes:  64%|██████▍   | 25950/40336 [01:47<00:58, 244.41it/s]

Leyendo pacientes:  64%|██████▍   | 25975/40336 [01:47<00:59, 242.86it/s]

Leyendo pacientes:  64%|██████▍   | 26004/40336 [01:47<00:56, 252.21it/s]

Leyendo pacientes:  65%|██████▍   | 26031/40336 [01:47<00:55, 257.11it/s]

Leyendo pacientes:  65%|██████▍   | 26057/40336 [01:47<00:57, 249.78it/s]

Leyendo pacientes:  65%|██████▍   | 26083/40336 [01:47<00:57, 248.90it/s]

Leyendo pacientes:  65%|██████▍   | 26111/40336 [01:47<00:56, 252.49it/s]

Leyendo pacientes:  65%|██████▍   | 26140/40336 [01:47<00:54, 261.53it/s]

Leyendo pacientes:  65%|██████▍   | 26167/40336 [01:48<00:55, 255.97it/s]

Leyendo pacientes:  65%|██████▍   | 26193/40336 [01:48<00:58, 242.33it/s]

Leyendo pacientes:  65%|██████▍   | 26218/40336 [01:48<01:01, 230.19it/s]

Leyendo pacientes:  65%|██████▌   | 26243/40336 [01:48<01:00, 231.70it/s]

Leyendo pacientes:  65%|██████▌   | 26272/40336 [01:48<00:57, 243.47it/s]

Leyendo pacientes:  65%|██████▌   | 26297/40336 [01:48<00:58, 239.98it/s]

Leyendo pacientes:  65%|██████▌   | 26322/40336 [01:48<00:58, 238.80it/s]

Leyendo pacientes:  65%|██████▌   | 26346/40336 [01:48<00:59, 236.79it/s]

Leyendo pacientes:  65%|██████▌   | 26370/40336 [01:48<01:01, 228.29it/s]

Leyendo pacientes:  65%|██████▌   | 26394/40336 [01:49<01:00, 229.84it/s]

Leyendo pacientes:  65%|██████▌   | 26419/40336 [01:49<00:59, 233.49it/s]

Leyendo pacientes:  66%|██████▌   | 26444/40336 [01:49<00:58, 237.83it/s]

Leyendo pacientes:  66%|██████▌   | 26471/40336 [01:49<00:56, 244.86it/s]

Leyendo pacientes:  66%|██████▌   | 26497/40336 [01:49<00:56, 244.98it/s]

Leyendo pacientes:  66%|██████▌   | 26524/40336 [01:49<00:55, 249.55it/s]

Leyendo pacientes:  66%|██████▌   | 26552/40336 [01:49<00:53, 257.74it/s]

Leyendo pacientes:  66%|██████▌   | 26579/40336 [01:49<00:52, 259.66it/s]

Leyendo pacientes:  66%|██████▌   | 26605/40336 [01:49<00:52, 259.14it/s]

Leyendo pacientes:  66%|██████▌   | 26631/40336 [01:50<00:54, 250.74it/s]

Leyendo pacientes:  66%|██████▌   | 26657/40336 [01:50<00:55, 246.19it/s]

Leyendo pacientes:  66%|██████▌   | 26684/40336 [01:50<00:54, 252.00it/s]

Leyendo pacientes:  66%|██████▌   | 26714/40336 [01:50<00:51, 265.45it/s]

Leyendo pacientes:  66%|██████▋   | 26744/40336 [01:50<00:50, 269.90it/s]

Leyendo pacientes:  66%|██████▋   | 26774/40336 [01:50<00:49, 271.48it/s]

Leyendo pacientes:  66%|██████▋   | 26805/40336 [01:50<00:48, 278.87it/s]

Leyendo pacientes:  67%|██████▋   | 26834/40336 [01:50<00:47, 281.54it/s]

Leyendo pacientes:  67%|██████▋   | 26863/40336 [01:50<00:48, 279.29it/s]

Leyendo pacientes:  67%|██████▋   | 26891/40336 [01:50<00:49, 273.93it/s]

Leyendo pacientes:  67%|██████▋   | 26919/40336 [01:51<00:50, 264.17it/s]

Leyendo pacientes:  67%|██████▋   | 26946/40336 [01:51<00:51, 260.17it/s]

Leyendo pacientes:  67%|██████▋   | 26974/40336 [01:51<00:50, 263.62it/s]

Leyendo pacientes:  67%|██████▋   | 27002/40336 [01:51<00:49, 267.44it/s]

Leyendo pacientes:  67%|██████▋   | 27029/40336 [01:51<00:50, 264.26it/s]

Leyendo pacientes:  67%|██████▋   | 27056/40336 [01:51<00:51, 260.14it/s]

Leyendo pacientes:  67%|██████▋   | 27083/40336 [01:51<00:51, 254.87it/s]

Leyendo pacientes:  67%|██████▋   | 27109/40336 [01:51<00:51, 255.49it/s]

Leyendo pacientes:  67%|██████▋   | 27136/40336 [01:51<00:51, 255.23it/s]

Leyendo pacientes:  67%|██████▋   | 27162/40336 [01:52<00:51, 255.44it/s]

Leyendo pacientes:  67%|██████▋   | 27188/40336 [01:52<00:52, 250.83it/s]

Leyendo pacientes:  67%|██████▋   | 27214/40336 [01:52<00:51, 252.85it/s]

Leyendo pacientes:  68%|██████▊   | 27243/40336 [01:52<00:50, 258.59it/s]

Leyendo pacientes:  68%|██████▊   | 27270/40336 [01:52<00:50, 260.25it/s]

Leyendo pacientes:  68%|██████▊   | 27297/40336 [01:52<00:50, 259.94it/s]

Leyendo pacientes:  68%|██████▊   | 27323/40336 [01:52<00:50, 255.32it/s]

Leyendo pacientes:  68%|██████▊   | 27349/40336 [01:52<00:50, 255.92it/s]

Leyendo pacientes:  68%|██████▊   | 27377/40336 [01:52<00:50, 257.51it/s]

Leyendo pacientes:  68%|██████▊   | 27404/40336 [01:52<00:50, 256.88it/s]

Leyendo pacientes:  68%|██████▊   | 27430/40336 [01:53<00:50, 256.74it/s]

Leyendo pacientes:  68%|██████▊   | 27456/40336 [01:53<00:50, 255.17it/s]

Leyendo pacientes:  68%|██████▊   | 27482/40336 [01:53<00:52, 247.11it/s]

Leyendo pacientes:  68%|██████▊   | 27507/40336 [01:53<00:56, 227.31it/s]

Leyendo pacientes:  68%|██████▊   | 27531/40336 [01:53<00:58, 217.87it/s]

Leyendo pacientes:  68%|██████▊   | 27554/40336 [01:53<00:59, 215.46it/s]

Leyendo pacientes:  68%|██████▊   | 27578/40336 [01:53<00:57, 221.79it/s]

Leyendo pacientes:  68%|██████▊   | 27603/40336 [01:53<00:56, 227.23it/s]

Leyendo pacientes:  68%|██████▊   | 27630/40336 [01:53<00:54, 233.95it/s]

Leyendo pacientes:  69%|██████▊   | 27657/40336 [01:54<00:52, 239.25it/s]

Leyendo pacientes:  69%|██████▊   | 27682/40336 [01:54<00:52, 242.23it/s]

Leyendo pacientes:  69%|██████▊   | 27707/40336 [01:54<00:51, 243.80it/s]

Leyendo pacientes:  69%|██████▉   | 27734/40336 [01:54<00:50, 251.01it/s]

Leyendo pacientes:  69%|██████▉   | 27760/40336 [01:54<00:53, 235.02it/s]

Leyendo pacientes:  69%|██████▉   | 27786/40336 [01:54<00:52, 240.18it/s]

Leyendo pacientes:  69%|██████▉   | 27813/40336 [01:54<00:50, 248.27it/s]

Leyendo pacientes:  69%|██████▉   | 27840/40336 [01:54<00:49, 253.53it/s]

Leyendo pacientes:  69%|██████▉   | 27866/40336 [01:54<00:50, 246.67it/s]

Leyendo pacientes:  69%|██████▉   | 27891/40336 [01:55<00:54, 229.91it/s]

Leyendo pacientes:  69%|██████▉   | 27915/40336 [01:55<00:53, 230.78it/s]

Leyendo pacientes:  69%|██████▉   | 27939/40336 [01:55<00:55, 224.40it/s]

Leyendo pacientes:  69%|██████▉   | 27965/40336 [01:55<00:54, 226.92it/s]

Leyendo pacientes:  69%|██████▉   | 27992/40336 [01:55<00:52, 237.19it/s]

Leyendo pacientes:  69%|██████▉   | 28016/40336 [01:55<00:52, 233.52it/s]

Leyendo pacientes:  70%|██████▉   | 28042/40336 [01:55<00:51, 239.88it/s]

Leyendo pacientes:  70%|██████▉   | 28069/40336 [01:55<00:49, 246.45it/s]

Leyendo pacientes:  70%|██████▉   | 28098/40336 [01:55<00:48, 253.83it/s]

Leyendo pacientes:  70%|██████▉   | 28124/40336 [01:56<00:49, 244.80it/s]

Leyendo pacientes:  70%|██████▉   | 28149/40336 [01:56<00:57, 211.63it/s]

Leyendo pacientes:  70%|██████▉   | 28178/40336 [01:56<00:52, 230.54it/s]

Leyendo pacientes:  70%|██████▉   | 28208/40336 [01:56<00:49, 247.07it/s]

Leyendo pacientes:  70%|███████   | 28241/40336 [01:56<00:45, 266.69it/s]

Leyendo pacientes:  70%|███████   | 28269/40336 [01:56<00:45, 267.55it/s]

Leyendo pacientes:  70%|███████   | 28297/40336 [01:56<00:44, 269.87it/s]

Leyendo pacientes:  70%|███████   | 28325/40336 [01:56<00:46, 259.44it/s]

Leyendo pacientes:  70%|███████   | 28352/40336 [01:56<00:46, 255.09it/s]

Leyendo pacientes:  70%|███████   | 28378/40336 [01:57<00:47, 252.54it/s]

Leyendo pacientes:  70%|███████   | 28405/40336 [01:57<00:47, 252.40it/s]

Leyendo pacientes:  70%|███████   | 28435/40336 [01:57<00:44, 265.89it/s]

Leyendo pacientes:  71%|███████   | 28465/40336 [01:57<00:43, 272.55it/s]

Leyendo pacientes:  71%|███████   | 28493/40336 [01:57<00:43, 272.78it/s]

Leyendo pacientes:  71%|███████   | 28521/40336 [01:57<00:43, 270.23it/s]

Leyendo pacientes:  71%|███████   | 28551/40336 [01:57<00:43, 273.93it/s]

Leyendo pacientes:  71%|███████   | 28579/40336 [01:57<00:42, 273.89it/s]

Leyendo pacientes:  71%|███████   | 28607/40336 [01:57<00:44, 262.23it/s]

Leyendo pacientes:  71%|███████   | 28634/40336 [01:57<00:47, 246.32it/s]

Leyendo pacientes:  71%|███████   | 28660/40336 [01:58<00:47, 246.90it/s]

Leyendo pacientes:  71%|███████   | 28687/40336 [01:58<00:46, 250.81it/s]

Leyendo pacientes:  71%|███████   | 28713/40336 [01:58<00:46, 248.87it/s]

Leyendo pacientes:  71%|███████▏  | 28743/40336 [01:58<00:45, 255.01it/s]

Leyendo pacientes:  71%|███████▏  | 28771/40336 [01:58<00:44, 259.46it/s]

Leyendo pacientes:  71%|███████▏  | 28798/40336 [01:58<00:44, 256.69it/s]

Leyendo pacientes:  71%|███████▏  | 28827/40336 [01:58<00:44, 259.64it/s]

Leyendo pacientes:  72%|███████▏  | 28853/40336 [01:58<00:44, 258.79it/s]

Leyendo pacientes:  72%|███████▏  | 28881/40336 [01:58<00:43, 263.04it/s]

Leyendo pacientes:  72%|███████▏  | 28908/40336 [01:59<00:43, 261.43it/s]

Leyendo pacientes:  72%|███████▏  | 28935/40336 [01:59<00:44, 258.18it/s]

Leyendo pacientes:  72%|███████▏  | 28962/40336 [01:59<00:43, 261.54it/s]

Leyendo pacientes:  72%|███████▏  | 28990/40336 [01:59<00:43, 263.21it/s]

Leyendo pacientes:  72%|███████▏  | 29018/40336 [01:59<00:43, 263.00it/s]

Leyendo pacientes:  72%|███████▏  | 29045/40336 [01:59<00:42, 264.87it/s]

Leyendo pacientes:  72%|███████▏  | 29072/40336 [01:59<00:42, 262.61it/s]

Leyendo pacientes:  72%|███████▏  | 29101/40336 [01:59<00:42, 264.70it/s]

Leyendo pacientes:  72%|███████▏  | 29128/40336 [01:59<00:42, 265.04it/s]

Leyendo pacientes:  72%|███████▏  | 29155/40336 [01:59<00:42, 260.22it/s]

Leyendo pacientes:  72%|███████▏  | 29182/40336 [02:00<00:43, 253.72it/s]

Leyendo pacientes:  72%|███████▏  | 29209/40336 [02:00<00:43, 254.29it/s]

Leyendo pacientes:  72%|███████▏  | 29239/40336 [02:00<00:42, 261.40it/s]

Leyendo pacientes:  73%|███████▎  | 29267/40336 [02:00<00:42, 261.42it/s]

Leyendo pacientes:  73%|███████▎  | 29295/40336 [02:00<00:42, 261.80it/s]

Leyendo pacientes:  73%|███████▎  | 29324/40336 [02:00<00:41, 264.96it/s]

Leyendo pacientes:  73%|███████▎  | 29353/40336 [02:00<00:40, 268.72it/s]

Leyendo pacientes:  73%|███████▎  | 29380/40336 [02:00<00:41, 264.32it/s]

Leyendo pacientes:  73%|███████▎  | 29407/40336 [02:00<00:42, 255.29it/s]

Leyendo pacientes:  73%|███████▎  | 29434/40336 [02:01<00:42, 256.62it/s]

Leyendo pacientes:  73%|███████▎  | 29460/40336 [02:01<00:43, 252.66it/s]

Leyendo pacientes:  73%|███████▎  | 29489/40336 [02:01<00:41, 258.48it/s]

Leyendo pacientes:  73%|███████▎  | 29519/40336 [02:01<00:40, 265.85it/s]

Leyendo pacientes:  73%|███████▎  | 29548/40336 [02:01<00:40, 268.36it/s]

Leyendo pacientes:  73%|███████▎  | 29575/40336 [02:01<00:40, 265.81it/s]

Leyendo pacientes:  73%|███████▎  | 29602/40336 [02:01<00:40, 264.90it/s]

Leyendo pacientes:  73%|███████▎  | 29631/40336 [02:01<00:39, 269.91it/s]

Leyendo pacientes:  74%|███████▎  | 29659/40336 [02:01<00:39, 270.64it/s]

Leyendo pacientes:  74%|███████▎  | 29687/40336 [02:02<00:39, 266.99it/s]

Leyendo pacientes:  74%|███████▎  | 29714/40336 [02:02<00:39, 265.73it/s]

Leyendo pacientes:  74%|███████▎  | 29741/40336 [02:02<00:40, 260.67it/s]

Leyendo pacientes:  74%|███████▍  | 29768/40336 [02:02<00:40, 260.75it/s]

Leyendo pacientes:  74%|███████▍  | 29795/40336 [02:02<00:40, 260.21it/s]

Leyendo pacientes:  74%|███████▍  | 29822/40336 [02:02<00:40, 258.66it/s]

Leyendo pacientes:  74%|███████▍  | 29848/40336 [02:02<00:41, 255.12it/s]

Leyendo pacientes:  74%|███████▍  | 29875/40336 [02:02<00:40, 259.20it/s]

Leyendo pacientes:  74%|███████▍  | 29904/40336 [02:02<00:39, 264.93it/s]

Leyendo pacientes:  74%|███████▍  | 29931/40336 [02:02<00:39, 263.77it/s]

Leyendo pacientes:  74%|███████▍  | 29958/40336 [02:03<00:39, 263.48it/s]

Leyendo pacientes:  74%|███████▍  | 29986/40336 [02:03<00:39, 262.36it/s]

Leyendo pacientes:  74%|███████▍  | 30013/40336 [02:03<00:39, 262.70it/s]

Leyendo pacientes:  74%|███████▍  | 30042/40336 [02:03<00:38, 266.58it/s]

Leyendo pacientes:  75%|███████▍  | 30071/40336 [02:03<00:38, 268.67it/s]

Leyendo pacientes:  75%|███████▍  | 30098/40336 [02:03<00:38, 265.02it/s]

Leyendo pacientes:  75%|███████▍  | 30125/40336 [02:03<00:38, 264.70it/s]

Leyendo pacientes:  75%|███████▍  | 30152/40336 [02:03<00:38, 263.03it/s]

Leyendo pacientes:  75%|███████▍  | 30179/40336 [02:03<00:38, 263.58it/s]

Leyendo pacientes:  75%|███████▍  | 30206/40336 [02:03<00:39, 255.05it/s]

Leyendo pacientes:  75%|███████▍  | 30232/40336 [02:04<00:41, 242.70it/s]

Leyendo pacientes:  75%|███████▌  | 30260/40336 [02:04<00:40, 249.73it/s]

Leyendo pacientes:  75%|███████▌  | 30287/40336 [02:04<00:39, 254.24it/s]

Leyendo pacientes:  75%|███████▌  | 30315/40336 [02:04<00:38, 259.38it/s]

Leyendo pacientes:  75%|███████▌  | 30345/40336 [02:04<00:37, 265.69it/s]

Leyendo pacientes:  75%|███████▌  | 30372/40336 [02:04<00:38, 262.15it/s]

Leyendo pacientes:  75%|███████▌  | 30400/40336 [02:04<00:37, 265.01it/s]

Leyendo pacientes:  75%|███████▌  | 30427/40336 [02:04<00:37, 265.11it/s]

Leyendo pacientes:  76%|███████▌  | 30456/40336 [02:04<00:36, 271.33it/s]

Leyendo pacientes:  76%|███████▌  | 30485/40336 [02:05<00:35, 274.21it/s]

Leyendo pacientes:  76%|███████▌  | 30513/40336 [02:05<00:37, 264.22it/s]

Leyendo pacientes:  76%|███████▌  | 30541/40336 [02:05<00:36, 264.86it/s]

Leyendo pacientes:  76%|███████▌  | 30568/40336 [02:07<05:06, 31.82it/s]

Leyendo pacientes:  76%|███████▌  | 30589/40336 [02:08<04:03, 40.03it/s]

Leyendo pacientes:  76%|███████▌  | 30614/40336 [02:08<03:03, 52.89it/s]

Leyendo pacientes:  76%|███████▌  | 30639/40336 [02:08<02:21, 68.58it/s]

Leyendo pacientes:  76%|███████▌  | 30666/40336 [02:08<01:48, 89.28it/s]

Leyendo pacientes:  76%|███████▌  | 30696/40336 [02:08<01:22, 116.38it/s]

Leyendo pacientes:  76%|███████▌  | 30727/40336 [02:08<01:06, 144.90it/s]

Leyendo pacientes:  76%|███████▌  | 30755/40336 [02:08<00:56, 168.64it/s]

Leyendo pacientes:  76%|███████▋  | 30783/40336 [02:08<00:50, 190.44it/s]

Leyendo pacientes:  76%|███████▋  | 30810/40336 [02:08<00:46, 205.21it/s]

Leyendo pacientes:  76%|███████▋  | 30837/40336 [02:08<00:43, 219.82it/s]

Leyendo pacientes:  77%|███████▋  | 30864/40336 [02:09<00:41, 230.51it/s]

Leyendo pacientes:  77%|███████▋  | 30891/40336 [02:09<00:41, 227.37it/s]

Leyendo pacientes:  77%|███████▋  | 30917/40336 [02:09<00:40, 231.57it/s]

Leyendo pacientes:  77%|███████▋  | 30942/40336 [02:09<00:40, 233.62it/s]

Leyendo pacientes:  77%|███████▋  | 30971/40336 [02:09<00:38, 244.93it/s]

Leyendo pacientes:  77%|███████▋  | 31002/40336 [02:09<00:36, 258.52it/s]

Leyendo pacientes:  77%|███████▋  | 31030/40336 [02:09<00:35, 264.28it/s]

Leyendo pacientes:  77%|███████▋  | 31059/40336 [02:09<00:34, 268.43it/s]

Leyendo pacientes:  77%|███████▋  | 31087/40336 [02:09<00:34, 265.64it/s]

Leyendo pacientes:  77%|███████▋  | 31115/40336 [02:10<00:34, 266.14it/s]

Leyendo pacientes:  77%|███████▋  | 31142/40336 [02:10<00:36, 251.68it/s]

Leyendo pacientes:  77%|███████▋  | 31168/40336 [02:10<00:37, 244.57it/s]

Leyendo pacientes:  77%|███████▋  | 31195/40336 [02:10<00:37, 246.92it/s]

Leyendo pacientes:  77%|███████▋  | 31224/40336 [02:10<00:35, 253.57it/s]

Leyendo pacientes:  77%|███████▋  | 31252/40336 [02:10<00:34, 259.77it/s]

Leyendo pacientes:  78%|███████▊  | 31279/40336 [02:10<00:35, 255.71it/s]

Leyendo pacientes:  78%|███████▊  | 31305/40336 [02:10<00:35, 255.75it/s]

Leyendo pacientes:  78%|███████▊  | 31331/40336 [02:10<00:35, 253.76it/s]

Leyendo pacientes:  78%|███████▊  | 31358/40336 [02:11<00:35, 252.90it/s]

Leyendo pacientes:  78%|███████▊  | 31387/40336 [02:11<00:34, 258.44it/s]

Leyendo pacientes:  78%|███████▊  | 31413/40336 [02:11<00:35, 254.91it/s]

Leyendo pacientes:  78%|███████▊  | 31441/40336 [02:11<00:34, 259.95it/s]

Leyendo pacientes:  78%|███████▊  | 31468/40336 [02:11<00:33, 262.14it/s]

Leyendo pacientes:  78%|███████▊  | 31495/40336 [02:11<00:33, 262.37it/s]

Leyendo pacientes:  78%|███████▊  | 31522/40336 [02:11<00:34, 252.95it/s]

Leyendo pacientes:  78%|███████▊  | 31548/40336 [02:11<00:35, 244.36it/s]

Leyendo pacientes:  78%|███████▊  | 31576/40336 [02:11<00:34, 253.32it/s]

Leyendo pacientes:  78%|███████▊  | 31602/40336 [02:11<00:35, 246.47it/s]

Leyendo pacientes:  78%|███████▊  | 31629/40336 [02:12<00:34, 249.14it/s]

Leyendo pacientes:  78%|███████▊  | 31654/40336 [02:12<00:36, 235.21it/s]

Leyendo pacientes:  79%|███████▊  | 31678/40336 [02:12<00:38, 224.28it/s]

Leyendo pacientes:  79%|███████▊  | 31701/40336 [02:12<00:39, 219.89it/s]

Leyendo pacientes:  79%|███████▊  | 31725/40336 [02:12<00:39, 220.64it/s]

Leyendo pacientes:  79%|███████▊  | 31752/40336 [02:12<00:37, 230.85it/s]

Leyendo pacientes:  79%|███████▉  | 31777/40336 [02:12<00:36, 235.84it/s]

Leyendo pacientes:  79%|███████▉  | 31805/40336 [02:12<00:34, 245.55it/s]

Leyendo pacientes:  79%|███████▉  | 31830/40336 [02:12<00:34, 245.34it/s]

Leyendo pacientes:  79%|███████▉  | 31857/40336 [02:13<00:33, 249.97it/s]

Leyendo pacientes:  79%|███████▉  | 31883/40336 [02:13<00:33, 250.03it/s]

Leyendo pacientes:  79%|███████▉  | 31909/40336 [02:13<00:33, 250.32it/s]

Leyendo pacientes:  79%|███████▉  | 31936/40336 [02:13<00:33, 253.62it/s]

Leyendo pacientes:  79%|███████▉  | 31964/40336 [02:13<00:32, 258.87it/s]

Leyendo pacientes:  79%|███████▉  | 31993/40336 [02:13<00:31, 262.79it/s]

Leyendo pacientes:  79%|███████▉  | 32020/40336 [02:13<00:31, 261.84it/s]

Leyendo pacientes:  79%|███████▉  | 32049/40336 [02:13<00:31, 264.39it/s]

Leyendo pacientes:  80%|███████▉  | 32077/40336 [02:13<00:30, 268.79it/s]

Leyendo pacientes:  80%|███████▉  | 32105/40336 [02:14<00:30, 267.83it/s]

Leyendo pacientes:  80%|███████▉  | 32132/40336 [02:14<00:30, 264.91it/s]

Leyendo pacientes:  80%|███████▉  | 32159/40336 [02:14<00:31, 261.78it/s]

Leyendo pacientes:  80%|███████▉  | 32190/40336 [02:14<00:30, 270.66it/s]

Leyendo pacientes:  80%|███████▉  | 32218/40336 [02:14<00:30, 268.88it/s]

Leyendo pacientes:  80%|███████▉  | 32245/40336 [02:14<00:30, 261.99it/s]

Leyendo pacientes:  80%|████████  | 32273/40336 [02:14<00:30, 261.56it/s]

Leyendo pacientes:  80%|████████  | 32304/40336 [02:14<00:29, 269.01it/s]

Leyendo pacientes:  80%|████████  | 32332/40336 [02:14<00:29, 268.73it/s]

Leyendo pacientes:  80%|████████  | 32359/40336 [02:14<00:30, 265.68it/s]

Leyendo pacientes:  80%|████████  | 32388/40336 [02:15<00:29, 268.12it/s]

Leyendo pacientes:  80%|████████  | 32415/40336 [02:15<00:30, 263.39it/s]

Leyendo pacientes:  80%|████████  | 32442/40336 [02:15<00:30, 261.67it/s]

Leyendo pacientes:  80%|████████  | 32469/40336 [02:15<00:29, 263.65it/s]

Leyendo pacientes:  81%|████████  | 32496/40336 [02:15<00:29, 261.44it/s]

Leyendo pacientes:  81%|████████  | 32525/40336 [02:15<00:29, 264.67it/s]

Leyendo pacientes:  81%|████████  | 32552/40336 [02:15<00:29, 262.31it/s]

Leyendo pacientes:  81%|████████  | 32580/40336 [02:15<00:29, 267.15it/s]

Leyendo pacientes:  81%|████████  | 32611/40336 [02:15<00:28, 273.46it/s]

Leyendo pacientes:  81%|████████  | 32639/40336 [02:16<00:28, 272.65it/s]

Leyendo pacientes:  81%|████████  | 32667/40336 [02:16<00:27, 274.57it/s]

Leyendo pacientes:  81%|████████  | 32695/40336 [02:16<00:28, 265.22it/s]

Leyendo pacientes:  81%|████████  | 32723/40336 [02:16<00:28, 264.33it/s]

Leyendo pacientes:  81%|████████  | 32750/40336 [02:16<00:29, 261.50it/s]

Leyendo pacientes:  81%|████████▏ | 32777/40336 [02:16<00:29, 259.14it/s]

Leyendo pacientes:  81%|████████▏ | 32803/40336 [02:16<00:29, 259.35it/s]

Leyendo pacientes:  81%|████████▏ | 32830/40336 [02:16<00:28, 260.89it/s]

Leyendo pacientes:  81%|████████▏ | 32857/40336 [02:16<00:29, 255.67it/s]

Leyendo pacientes:  82%|████████▏ | 32883/40336 [02:16<00:29, 250.57it/s]

Leyendo pacientes:  82%|████████▏ | 32909/40336 [02:17<00:29, 249.30it/s]

Leyendo pacientes:  82%|████████▏ | 32935/40336 [02:17<00:29, 252.10it/s]

Leyendo pacientes:  82%|████████▏ | 32961/40336 [02:17<00:29, 253.19it/s]

Leyendo pacientes:  82%|████████▏ | 32990/40336 [02:17<00:27, 263.19it/s]

Leyendo pacientes:  82%|████████▏ | 33017/40336 [02:17<00:27, 263.94it/s]

Leyendo pacientes:  82%|████████▏ | 33044/40336 [02:17<00:27, 262.95it/s]

Leyendo pacientes:  82%|████████▏ | 33071/40336 [02:17<00:27, 261.55it/s]

Leyendo pacientes:  82%|████████▏ | 33099/40336 [02:17<00:27, 264.34it/s]

Leyendo pacientes:  82%|████████▏ | 33126/40336 [02:17<00:27, 260.95it/s]

Leyendo pacientes:  82%|████████▏ | 33156/40336 [02:17<00:27, 265.84it/s]

Leyendo pacientes:  82%|████████▏ | 33183/40336 [02:18<00:27, 262.79it/s]

Leyendo pacientes:  82%|████████▏ | 33210/40336 [02:18<00:27, 258.91it/s]

Leyendo pacientes:  82%|████████▏ | 33238/40336 [02:18<00:27, 260.58it/s]

Leyendo pacientes:  82%|████████▏ | 33265/40336 [02:18<00:27, 258.76it/s]

Leyendo pacientes:  83%|████████▎ | 33294/40336 [02:18<00:26, 261.47it/s]

Leyendo pacientes:  83%|████████▎ | 33322/40336 [02:18<00:26, 264.01it/s]

Leyendo pacientes:  83%|████████▎ | 33350/40336 [02:18<00:26, 268.26it/s]

Leyendo pacientes:  83%|████████▎ | 33377/40336 [02:18<00:26, 258.14it/s]

Leyendo pacientes:  83%|████████▎ | 33406/40336 [02:18<00:26, 262.61it/s]

Leyendo pacientes:  83%|████████▎ | 33434/40336 [02:19<00:26, 263.07it/s]

Leyendo pacientes:  83%|████████▎ | 33461/40336 [02:19<00:26, 260.30it/s]

Leyendo pacientes:  83%|████████▎ | 33490/40336 [02:19<00:25, 267.08it/s]

Leyendo pacientes:  83%|████████▎ | 33517/40336 [02:19<00:25, 263.10it/s]

Leyendo pacientes:  83%|████████▎ | 33544/40336 [02:19<00:26, 260.19it/s]

Leyendo pacientes:  83%|████████▎ | 33572/40336 [02:19<00:25, 261.70it/s]

Leyendo pacientes:  83%|████████▎ | 33599/40336 [02:19<00:25, 263.96it/s]

Leyendo pacientes:  83%|████████▎ | 33628/40336 [02:19<00:25, 267.40it/s]

Leyendo pacientes:  83%|████████▎ | 33655/40336 [02:19<00:25, 266.76it/s]

Leyendo pacientes:  84%|████████▎ | 33682/40336 [02:19<00:25, 265.91it/s]

Leyendo pacientes:  84%|████████▎ | 33709/40336 [02:20<00:25, 263.10it/s]

Leyendo pacientes:  84%|████████▎ | 33736/40336 [02:20<00:25, 256.35it/s]

Leyendo pacientes:  84%|████████▎ | 33762/40336 [02:20<00:25, 254.55it/s]

Leyendo pacientes:  84%|████████▍ | 33788/40336 [02:20<00:26, 251.48it/s]

Leyendo pacientes:  84%|████████▍ | 33816/40336 [02:20<00:25, 254.18it/s]

Leyendo pacientes:  84%|████████▍ | 33842/40336 [02:20<00:25, 252.04it/s]

Leyendo pacientes:  84%|████████▍ | 33869/40336 [02:20<00:25, 252.81it/s]

Leyendo pacientes:  84%|████████▍ | 33898/40336 [02:20<00:24, 258.31it/s]

Leyendo pacientes:  84%|████████▍ | 33925/40336 [02:20<00:25, 255.93it/s]

Leyendo pacientes:  84%|████████▍ | 33953/40336 [02:21<00:24, 256.60it/s]

Leyendo pacientes:  84%|████████▍ | 33979/40336 [02:21<00:25, 253.56it/s]

Leyendo pacientes:  84%|████████▍ | 34006/40336 [02:21<00:24, 255.49it/s]

Leyendo pacientes:  84%|████████▍ | 34035/40336 [02:21<00:23, 265.38it/s]

Leyendo pacientes:  84%|████████▍ | 34063/40336 [02:21<00:23, 263.42it/s]

Leyendo pacientes:  85%|████████▍ | 34090/40336 [02:21<00:23, 261.19it/s]

Leyendo pacientes:  85%|████████▍ | 34118/40336 [02:21<00:23, 260.54it/s]

Leyendo pacientes:  85%|████████▍ | 34145/40336 [02:21<00:23, 258.34it/s]

Leyendo pacientes:  85%|████████▍ | 34171/40336 [02:21<00:24, 250.85it/s]

Leyendo pacientes:  85%|████████▍ | 34197/40336 [02:22<00:24, 251.70it/s]

Leyendo pacientes:  85%|████████▍ | 34223/40336 [02:22<00:24, 248.92it/s]

Leyendo pacientes:  85%|████████▍ | 34249/40336 [02:22<00:24, 248.50it/s]

Leyendo pacientes:  85%|████████▍ | 34275/40336 [02:22<00:24, 251.35it/s]

Leyendo pacientes:  85%|████████▌ | 34303/40336 [02:22<00:23, 258.65it/s]

Leyendo pacientes:  85%|████████▌ | 34329/40336 [02:22<00:23, 258.70it/s]

Leyendo pacientes:  85%|████████▌ | 34360/40336 [02:22<00:22, 268.23it/s]

Leyendo pacientes:  85%|████████▌ | 34387/40336 [02:22<00:22, 266.83it/s]

Leyendo pacientes:  85%|████████▌ | 34416/40336 [02:22<00:22, 268.31it/s]

Leyendo pacientes:  85%|████████▌ | 34444/40336 [02:22<00:22, 265.03it/s]

Leyendo pacientes:  85%|████████▌ | 34472/40336 [02:23<00:22, 265.81it/s]

Leyendo pacientes:  86%|████████▌ | 34499/40336 [02:23<00:21, 265.93it/s]

Leyendo pacientes:  86%|████████▌ | 34526/40336 [02:23<00:22, 263.31it/s]

Leyendo pacientes:  86%|████████▌ | 34553/40336 [02:23<00:22, 258.14it/s]

Leyendo pacientes:  86%|████████▌ | 34579/40336 [02:23<00:22, 256.16it/s]

Leyendo pacientes:  86%|████████▌ | 34607/40336 [02:23<00:22, 257.03it/s]

Leyendo pacientes:  86%|████████▌ | 34633/40336 [02:23<00:22, 257.28it/s]

Leyendo pacientes:  86%|████████▌ | 34661/40336 [02:23<00:21, 260.26it/s]

Leyendo pacientes:  86%|████████▌ | 34688/40336 [02:23<00:21, 260.56it/s]

Leyendo pacientes:  86%|████████▌ | 34716/40336 [02:24<00:21, 264.03it/s]

Leyendo pacientes:  86%|████████▌ | 34744/40336 [02:24<00:21, 263.86it/s]

Leyendo pacientes:  86%|████████▌ | 34771/40336 [02:24<00:21, 258.58it/s]

Leyendo pacientes:  86%|████████▋ | 34797/40336 [02:24<00:21, 258.82it/s]

Leyendo pacientes:  86%|████████▋ | 34824/40336 [02:24<00:21, 259.80it/s]

Leyendo pacientes:  86%|████████▋ | 34850/40336 [02:24<00:21, 259.26it/s]

Leyendo pacientes:  86%|████████▋ | 34878/40336 [02:24<00:20, 261.76it/s]

Leyendo pacientes:  87%|████████▋ | 34905/40336 [02:24<00:20, 258.96it/s]

Leyendo pacientes:  87%|████████▋ | 34933/40336 [02:24<00:20, 260.97it/s]

Leyendo pacientes:  87%|████████▋ | 34961/40336 [02:24<00:20, 261.43it/s]

Leyendo pacientes:  87%|████████▋ | 34988/40336 [02:25<00:20, 259.83it/s]

Leyendo pacientes:  87%|████████▋ | 35014/40336 [02:25<00:20, 254.99it/s]

Leyendo pacientes:  87%|████████▋ | 35040/40336 [02:25<00:20, 252.25it/s]

Leyendo pacientes:  87%|████████▋ | 35066/40336 [02:25<00:21, 246.51it/s]

Leyendo pacientes:  87%|████████▋ | 35091/40336 [02:25<00:21, 241.27it/s]

Leyendo pacientes:  87%|████████▋ | 35117/40336 [02:25<00:21, 246.14it/s]

Leyendo pacientes:  87%|████████▋ | 35147/40336 [02:25<00:20, 255.46it/s]

Leyendo pacientes:  87%|████████▋ | 35175/40336 [02:25<00:20, 257.65it/s]

Leyendo pacientes:  87%|████████▋ | 35202/40336 [02:25<00:20, 256.07it/s]

Leyendo pacientes:  87%|████████▋ | 35228/40336 [02:26<00:20, 253.36it/s]

Leyendo pacientes:  87%|████████▋ | 35255/40336 [02:26<00:19, 254.43it/s]

Leyendo pacientes:  87%|████████▋ | 35282/40336 [02:26<00:19, 258.54it/s]

Leyendo pacientes:  88%|████████▊ | 35308/40336 [02:26<00:19, 256.14it/s]

Leyendo pacientes:  88%|████████▊ | 35336/40336 [02:26<00:19, 260.62it/s]

Leyendo pacientes:  88%|████████▊ | 35363/40336 [02:26<00:19, 257.94it/s]

Leyendo pacientes:  88%|████████▊ | 35389/40336 [02:26<00:19, 256.66it/s]

Leyendo pacientes:  88%|████████▊ | 35418/40336 [02:26<00:18, 261.85it/s]

Leyendo pacientes:  88%|████████▊ | 35446/40336 [02:26<00:18, 261.75it/s]

Leyendo pacientes:  88%|████████▊ | 35475/40336 [02:26<00:18, 264.71it/s]

Leyendo pacientes:  88%|████████▊ | 35502/40336 [02:27<00:18, 265.50it/s]

Leyendo pacientes:  88%|████████▊ | 35529/40336 [02:27<00:18, 257.72it/s]

Leyendo pacientes:  88%|████████▊ | 35555/40336 [02:27<00:18, 255.62it/s]

Leyendo pacientes:  88%|████████▊ | 35583/40336 [02:27<00:18, 261.53it/s]

Leyendo pacientes:  88%|████████▊ | 35611/40336 [02:27<00:17, 266.14it/s]

Leyendo pacientes:  88%|████████▊ | 35638/40336 [02:27<00:17, 266.18it/s]

Leyendo pacientes:  88%|████████▊ | 35665/40336 [02:27<00:17, 263.43it/s]

Leyendo pacientes:  88%|████████▊ | 35692/40336 [02:27<00:17, 260.05it/s]

Leyendo pacientes:  89%|████████▊ | 35720/40336 [02:27<00:17, 260.13it/s]

Leyendo pacientes:  89%|████████▊ | 35749/40336 [02:28<00:17, 262.31it/s]

Leyendo pacientes:  89%|████████▊ | 35776/40336 [02:28<00:17, 260.05it/s]

Leyendo pacientes:  89%|████████▉ | 35805/40336 [02:28<00:17, 262.72it/s]

Leyendo pacientes:  89%|████████▉ | 35832/40336 [02:28<00:17, 264.02it/s]

Leyendo pacientes:  89%|████████▉ | 35859/40336 [02:28<00:17, 260.48it/s]

Leyendo pacientes:  89%|████████▉ | 35887/40336 [02:28<00:16, 263.60it/s]

Leyendo pacientes:  89%|████████▉ | 35914/40336 [02:28<00:17, 258.96it/s]

Leyendo pacientes:  89%|████████▉ | 35943/40336 [02:28<00:16, 264.62it/s]

Leyendo pacientes:  89%|████████▉ | 35970/40336 [02:28<00:16, 265.19it/s]

Leyendo pacientes:  89%|████████▉ | 35997/40336 [02:28<00:16, 260.58it/s]

Leyendo pacientes:  89%|████████▉ | 36026/40336 [02:29<00:16, 265.10it/s]

Leyendo pacientes:  89%|████████▉ | 36053/40336 [02:29<00:16, 261.60it/s]

Leyendo pacientes:  89%|████████▉ | 36081/40336 [02:29<00:16, 263.38it/s]

Leyendo pacientes:  90%|████████▉ | 36108/40336 [02:29<00:16, 261.57it/s]

Leyendo pacientes:  90%|████████▉ | 36135/40336 [02:29<00:16, 254.36it/s]

Leyendo pacientes:  90%|████████▉ | 36161/40336 [02:29<00:16, 253.98it/s]

Leyendo pacientes:  90%|████████▉ | 36187/40336 [02:29<00:16, 252.77it/s]

Leyendo pacientes:  90%|████████▉ | 36214/40336 [02:29<00:15, 257.69it/s]

Leyendo pacientes:  90%|████████▉ | 36242/40336 [02:29<00:15, 261.13it/s]

Leyendo pacientes:  90%|████████▉ | 36270/40336 [02:30<00:15, 262.44it/s]

Leyendo pacientes:  90%|████████▉ | 36297/40336 [02:30<00:15, 256.80it/s]

Leyendo pacientes:  90%|█████████ | 36324/40336 [02:30<00:15, 257.35it/s]

Leyendo pacientes:  90%|█████████ | 36352/40336 [02:30<00:15, 261.16it/s]

Leyendo pacientes:  90%|█████████ | 36379/40336 [02:30<00:15, 261.65it/s]

Leyendo pacientes:  90%|█████████ | 36406/40336 [02:30<00:15, 259.89it/s]

Leyendo pacientes:  90%|█████████ | 36433/40336 [02:30<00:15, 257.10it/s]

Leyendo pacientes:  90%|█████████ | 36460/40336 [02:30<00:15, 258.25it/s]

Leyendo pacientes:  90%|█████████ | 36487/40336 [02:30<00:14, 260.95it/s]

Leyendo pacientes:  91%|█████████ | 36515/40336 [02:30<00:14, 265.85it/s]

Leyendo pacientes:  91%|█████████ | 36542/40336 [02:31<00:14, 260.50it/s]

Leyendo pacientes:  91%|█████████ | 36569/40336 [02:31<00:14, 262.84it/s]

Leyendo pacientes:  91%|█████████ | 36597/40336 [02:31<00:14, 262.53it/s]

Leyendo pacientes:  91%|█████████ | 36625/40336 [02:31<00:14, 263.21it/s]

Leyendo pacientes:  91%|█████████ | 36652/40336 [02:31<00:14, 261.05it/s]

Leyendo pacientes:  91%|█████████ | 36679/40336 [02:31<00:14, 258.14it/s]

Leyendo pacientes:  91%|█████████ | 36706/40336 [02:31<00:14, 258.39it/s]

Leyendo pacientes:  91%|█████████ | 36734/40336 [02:31<00:13, 261.97it/s]

Leyendo pacientes:  91%|█████████ | 36762/40336 [02:31<00:13, 261.65it/s]

Leyendo pacientes:  91%|█████████ | 36789/40336 [02:31<00:13, 261.32it/s]

Leyendo pacientes:  91%|█████████▏| 36816/40336 [02:32<00:13, 256.59it/s]

Leyendo pacientes:  91%|█████████▏| 36842/40336 [02:32<00:13, 254.57it/s]

Leyendo pacientes:  91%|█████████▏| 36868/40336 [02:32<00:13, 255.75it/s]

Leyendo pacientes:  91%|█████████▏| 36894/40336 [02:32<00:13, 249.47it/s]

Leyendo pacientes:  92%|█████████▏| 36921/40336 [02:32<00:13, 254.60it/s]

Leyendo pacientes:  92%|█████████▏| 36948/40336 [02:32<00:13, 255.29it/s]

Leyendo pacientes:  92%|█████████▏| 36974/40336 [02:32<00:13, 255.67it/s]

Leyendo pacientes:  92%|█████████▏| 37000/40336 [02:32<00:13, 255.06it/s]

Leyendo pacientes:  92%|█████████▏| 37027/40336 [02:32<00:12, 256.91it/s]

Leyendo pacientes:  92%|█████████▏| 37054/40336 [02:33<00:12, 259.63it/s]

Leyendo pacientes:  92%|█████████▏| 37081/40336 [02:33<00:12, 258.64it/s]

Leyendo pacientes:  92%|█████████▏| 37109/40336 [02:33<00:12, 257.86it/s]

Leyendo pacientes:  92%|█████████▏| 37136/40336 [02:33<00:12, 258.91it/s]

Leyendo pacientes:  92%|█████████▏| 37164/40336 [02:33<00:12, 262.70it/s]

Leyendo pacientes:  92%|█████████▏| 37192/40336 [02:33<00:11, 266.18it/s]

Leyendo pacientes:  92%|█████████▏| 37221/40336 [02:33<00:11, 271.17it/s]

Leyendo pacientes:  92%|█████████▏| 37249/40336 [02:33<00:11, 272.56it/s]

Leyendo pacientes:  92%|█████████▏| 37277/40336 [02:33<00:11, 264.87it/s]

Leyendo pacientes:  92%|█████████▏| 37304/40336 [02:33<00:11, 260.14it/s]

Leyendo pacientes:  93%|█████████▎| 37331/40336 [02:34<00:11, 261.18it/s]

Leyendo pacientes:  93%|█████████▎| 37358/40336 [02:34<00:11, 260.62it/s]

Leyendo pacientes:  93%|█████████▎| 37385/40336 [02:34<00:11, 260.45it/s]

Leyendo pacientes:  93%|█████████▎| 37412/40336 [02:34<00:11, 258.17it/s]

Leyendo pacientes:  93%|█████████▎| 37438/40336 [02:34<00:11, 254.30it/s]

Leyendo pacientes:  93%|█████████▎| 37464/40336 [02:34<00:11, 250.96it/s]

Leyendo pacientes:  93%|█████████▎| 37490/40336 [02:34<00:11, 249.28it/s]

Leyendo pacientes:  93%|█████████▎| 37520/40336 [02:34<00:10, 259.28it/s]

Leyendo pacientes:  93%|█████████▎| 37547/40336 [02:34<00:10, 257.45it/s]

Leyendo pacientes:  93%|█████████▎| 37573/40336 [02:35<00:10, 255.68it/s]

Leyendo pacientes:  93%|█████████▎| 37599/40336 [02:35<00:10, 256.37it/s]

Leyendo pacientes:  93%|█████████▎| 37625/40336 [02:35<00:10, 256.29it/s]

Leyendo pacientes:  93%|█████████▎| 37653/40336 [02:35<00:10, 261.56it/s]

Leyendo pacientes:  93%|█████████▎| 37682/40336 [02:35<00:10, 264.36it/s]

Leyendo pacientes:  93%|█████████▎| 37710/40336 [02:35<00:09, 267.89it/s]

Leyendo pacientes:  94%|█████████▎| 37737/40336 [02:35<00:09, 262.13it/s]

Leyendo pacientes:  94%|█████████▎| 37764/40336 [02:35<00:09, 264.27it/s]

Leyendo pacientes:  94%|█████████▎| 37791/40336 [02:35<00:09, 258.26it/s]

Leyendo pacientes:  94%|█████████▍| 37819/40336 [02:35<00:09, 262.86it/s]

Leyendo pacientes:  94%|█████████▍| 37846/40336 [02:36<00:09, 259.91it/s]

Leyendo pacientes:  94%|█████████▍| 37873/40336 [02:36<00:09, 258.90it/s]

Leyendo pacientes:  94%|█████████▍| 37900/40336 [02:36<00:09, 259.86it/s]

Leyendo pacientes:  94%|█████████▍| 37929/40336 [02:36<00:09, 266.20it/s]

Leyendo pacientes:  94%|█████████▍| 37958/40336 [02:36<00:08, 267.53it/s]

Leyendo pacientes:  94%|█████████▍| 37985/40336 [02:36<00:08, 267.99it/s]

Leyendo pacientes:  94%|█████████▍| 38012/40336 [02:36<00:08, 260.62it/s]

Leyendo pacientes:  94%|█████████▍| 38039/40336 [02:36<00:08, 261.47it/s]

Leyendo pacientes:  94%|█████████▍| 38066/40336 [02:36<00:08, 258.17it/s]

Leyendo pacientes:  94%|█████████▍| 38092/40336 [02:37<00:08, 254.39it/s]

Leyendo pacientes:  95%|█████████▍| 38118/40336 [02:37<00:08, 252.04it/s]

Leyendo pacientes:  95%|█████████▍| 38145/40336 [02:37<00:08, 252.43it/s]

Leyendo pacientes:  95%|█████████▍| 38173/40336 [02:37<00:08, 255.22it/s]

Leyendo pacientes:  95%|█████████▍| 38201/40336 [02:37<00:08, 257.14it/s]

Leyendo pacientes:  95%|█████████▍| 38228/40336 [02:37<00:08, 259.56it/s]

Leyendo pacientes:  95%|█████████▍| 38255/40336 [02:37<00:08, 256.41it/s]

Leyendo pacientes:  95%|█████████▍| 38283/40336 [02:37<00:07, 257.68it/s]

Leyendo pacientes:  95%|█████████▍| 38310/40336 [02:37<00:07, 259.76it/s]

Leyendo pacientes:  95%|█████████▌| 38337/40336 [02:37<00:07, 260.49it/s]

Leyendo pacientes:  95%|█████████▌| 38364/40336 [02:38<00:07, 255.70it/s]

Leyendo pacientes:  95%|█████████▌| 38390/40336 [02:38<00:07, 255.59it/s]

Leyendo pacientes:  95%|█████████▌| 38418/40336 [02:38<00:07, 256.86it/s]

Leyendo pacientes:  95%|█████████▌| 38444/40336 [02:41<01:09, 27.22it/s]

Leyendo pacientes:  95%|█████████▌| 38471/40336 [02:41<00:49, 37.32it/s]

Leyendo pacientes:  95%|█████████▌| 38500/40336 [02:41<00:35, 51.33it/s]

Leyendo pacientes:  96%|█████████▌| 38527/40336 [02:41<00:26, 67.20it/s]

Leyendo pacientes:  96%|█████████▌| 38554/40336 [02:41<00:20, 86.08it/s]

Leyendo pacientes:  96%|█████████▌| 38581/40336 [02:41<00:16, 107.81it/s]

Leyendo pacientes:  96%|█████████▌| 38608/40336 [02:41<00:13, 130.74it/s]

Leyendo pacientes:  96%|█████████▌| 38634/40336 [02:42<00:11, 152.82it/s]

Leyendo pacientes:  96%|█████████▌| 38660/40336 [02:42<00:09, 172.63it/s]

Leyendo pacientes:  96%|█████████▌| 38688/40336 [02:42<00:08, 193.28it/s]

Leyendo pacientes:  96%|█████████▌| 38715/40336 [02:42<00:07, 210.68it/s]

Leyendo pacientes:  96%|█████████▌| 38741/40336 [02:42<00:07, 210.89it/s]

Leyendo pacientes:  96%|█████████▌| 38766/40336 [02:42<00:07, 213.80it/s]

Leyendo pacientes:  96%|█████████▌| 38794/40336 [02:42<00:06, 227.31it/s]

Leyendo pacientes:  96%|█████████▌| 38823/40336 [02:42<00:06, 239.90it/s]

Leyendo pacientes:  96%|█████████▋| 38849/40336 [02:42<00:06, 242.79it/s]

Leyendo pacientes:  96%|█████████▋| 38877/40336 [02:43<00:05, 252.82it/s]

Leyendo pacientes:  96%|█████████▋| 38904/40336 [02:43<00:05, 252.91it/s]

Leyendo pacientes:  97%|█████████▋| 38930/40336 [02:43<00:05, 252.11it/s]

Leyendo pacientes:  97%|█████████▋| 38956/40336 [02:43<00:05, 252.00it/s]

Leyendo pacientes:  97%|█████████▋| 38982/40336 [02:43<00:05, 249.24it/s]

Leyendo pacientes:  97%|█████████▋| 39008/40336 [02:43<00:05, 252.04it/s]

Leyendo pacientes:  97%|█████████▋| 39034/40336 [02:43<00:05, 247.60it/s]

Leyendo pacientes:  97%|█████████▋| 39059/40336 [02:43<00:05, 245.98it/s]

Leyendo pacientes:  97%|█████████▋| 39086/40336 [02:43<00:04, 250.85it/s]

Leyendo pacientes:  97%|█████████▋| 39113/40336 [02:43<00:04, 250.94it/s]

Leyendo pacientes:  97%|█████████▋| 39141/40336 [02:44<00:04, 255.39it/s]

Leyendo pacientes:  97%|█████████▋| 39167/40336 [02:44<00:04, 251.48it/s]

Leyendo pacientes:  97%|█████████▋| 39193/40336 [02:44<00:04, 252.93it/s]

Leyendo pacientes:  97%|█████████▋| 39219/40336 [02:44<00:04, 242.90it/s]

Leyendo pacientes:  97%|█████████▋| 39245/40336 [02:44<00:04, 247.31it/s]

Leyendo pacientes:  97%|█████████▋| 39272/40336 [02:44<00:04, 253.27it/s]

Leyendo pacientes:  97%|█████████▋| 39298/40336 [02:44<00:04, 252.10it/s]

Leyendo pacientes:  97%|█████████▋| 39326/40336 [02:44<00:03, 253.73it/s]

Leyendo pacientes:  98%|█████████▊| 39352/40336 [02:44<00:03, 255.46it/s]

Leyendo pacientes:  98%|█████████▊| 39378/40336 [02:45<00:03, 256.09it/s]

Leyendo pacientes:  98%|█████████▊| 39404/40336 [02:45<00:03, 254.74it/s]

Leyendo pacientes:  98%|█████████▊| 39430/40336 [02:45<00:03, 247.92it/s]

Leyendo pacientes:  98%|█████████▊| 39455/40336 [02:45<00:03, 247.92it/s]

Leyendo pacientes:  98%|█████████▊| 39481/40336 [02:45<00:03, 248.62it/s]

Leyendo pacientes:  98%|█████████▊| 39509/40336 [02:45<00:03, 257.05it/s]

Leyendo pacientes:  98%|█████████▊| 39536/40336 [02:45<00:03, 258.96it/s]

Leyendo pacientes:  98%|█████████▊| 39563/40336 [02:45<00:02, 259.64it/s]

Leyendo pacientes:  98%|█████████▊| 39591/40336 [02:45<00:02, 265.12it/s]

Leyendo pacientes:  98%|█████████▊| 39619/40336 [02:45<00:02, 265.66it/s]

Leyendo pacientes:  98%|█████████▊| 39647/40336 [02:46<00:02, 264.44it/s]

Leyendo pacientes:  98%|█████████▊| 39674/40336 [02:46<00:02, 260.79it/s]

Leyendo pacientes:  98%|█████████▊| 39701/40336 [02:46<00:02, 259.07it/s]

Leyendo pacientes:  98%|█████████▊| 39728/40336 [02:46<00:02, 257.52it/s]

Leyendo pacientes:  99%|█████████▊| 39756/40336 [02:46<00:02, 257.27it/s]

Leyendo pacientes:  99%|█████████▊| 39783/40336 [02:46<00:02, 257.52it/s]

Leyendo pacientes:  99%|█████████▊| 39809/40336 [02:46<00:02, 254.01it/s]

Leyendo pacientes:  99%|█████████▉| 39835/40336 [02:46<00:01, 252.60it/s]

Leyendo pacientes:  99%|█████████▉| 39861/40336 [02:46<00:01, 253.16it/s]

Leyendo pacientes:  99%|█████████▉| 39887/40336 [02:46<00:01, 253.77it/s]

Leyendo pacientes:  99%|█████████▉| 39913/40336 [02:47<00:01, 254.12it/s]

Leyendo pacientes:  99%|█████████▉| 39939/40336 [02:47<00:01, 248.84it/s]

Leyendo pacientes:  99%|█████████▉| 39967/40336 [02:47<00:01, 253.19it/s]

Leyendo pacientes:  99%|█████████▉| 39994/40336 [02:47<00:01, 254.65it/s]

Leyendo pacientes:  99%|█████████▉| 40022/40336 [02:47<00:01, 261.54it/s]

Leyendo pacientes:  99%|█████████▉| 40050/40336 [02:47<00:01, 262.96it/s]

Leyendo pacientes:  99%|█████████▉| 40077/40336 [02:47<00:00, 260.49it/s]

Leyendo pacientes:  99%|█████████▉| 40104/40336 [02:47<00:00, 258.16it/s]

Leyendo pacientes:  99%|█████████▉| 40132/40336 [02:47<00:00, 257.82it/s]

Leyendo pacientes: 100%|█████████▉| 40158/40336 [02:48<00:00, 247.70it/s]

Leyendo pacientes: 100%|█████████▉| 40186/40336 [02:48<00:00, 254.20it/s]

Leyendo pacientes: 100%|█████████▉| 40216/40336 [02:48<00:00, 260.95it/s]

Leyendo pacientes: 100%|█████████▉| 40243/40336 [02:48<00:00, 259.57it/s]

Leyendo pacientes: 100%|█████████▉| 40269/40336 [02:48<00:00, 259.22it/s]

Leyendo pacientes: 100%|█████████▉| 40295/40336 [02:48<00:00, 254.77it/s]

Leyendo pacientes: 100%|█████████▉| 40321/40336 [02:48<00:00, 253.31it/s]

Leyendo pacientes: 100%|██████████| 40336/40336 [02:48<00:00, 239.04it/s]

1,552,210 filas-hora | 40,336 pacientes | 43 columnas
Memoria: 243 MB

## 4. Auditoría de integridad

Todo el proyecto se apoya en cuatro supuestos. Si alguno falla, se rompen cosas más adelante
de forma silenciosa, así que los verificamos ahora en vez de asumirlos.

### 4.1 ¿El reloj (`ICULOS`) es limpio?

Vamos a construir ventanas temporales (media de las últimas 6 h, pendiente de las últimas 24 h).
Eso presupone que las filas de un paciente están **ordenadas y son consecutivas hora a hora**.
Si hubiera saltos, una "ventana de 6 filas" no sería una ventana de 6 horas y las features
quedarían mal definidas.

In [6]:
reloj = df.groupby("pid", observed=True)["ICULOS"].agg(["min", "max", "count"])
contiguo = (reloj["max"] - reloj["min"] + 1 == reloj["count"])
empieza_en_1 = (reloj["min"] == 1)
ordenado = df.groupby("pid", observed=True)["ICULOS"].is_monotonic_increasing.all()

pd.Series({
    "pacientes con ICULOS contiguo (sin huecos)": f"{contiguo.mean() * 100:.2f} %",
    "pacientes que empiezan en ICULOS = 1": f"{empieza_en_1.mean() * 100:.2f} %",
    "orden correcto dentro de cada paciente": str(ordenado),
}).to_frame("resultado")

                                           resultado
pacientes con ICULOS contiguo (sin huecos)  100.00 %
pacientes que empiezan en ICULOS = 1         78.20 %
orden correcto dentro de cada paciente          True

La buena noticia es que **no hay un solo hueco**: dentro de cada paciente las horas son
consecutivas, así que las ventanas rodantes son válidas.

Pero aparece algo que no esperábamos: **el 21,8 % de los pacientes no empieza en `ICULOS = 1`**.
Su registro arranca en la hora 2, 3, 5... Esto no es un hueco intermedio, es un arranque tardío,
y merece explicación antes de seguir. Veamos dónde se concentra:

In [7]:
resumen_inicio = reloj.assign(
    inicio_tardio=~empieza_en_1,
    hosp=df.groupby("pid", observed=True)["hosp"].first(),
    septico=df.groupby("pid", observed=True)["SepsisLabel"].max(),
)

resumen_inicio.groupby(["hosp", "inicio_tardio"], observed=True).agg(
    n_pacientes=("count", "size"),
    horas_mediana=("count", "median"),
    prev_sepsis_=("septico", lambda s: round(s.mean() * 100, 1)),
)

                    n_pacientes  horas_mediana  prev_sepsis_
hosp inicio_tardio
A    False                12839           39.0           9.5
     True                  7497           37.0           7.7
B    False                18704           38.0           5.7
     True                  1296           37.0           6.4

El patrón es claro y es **una diferencia entre hospitales, no un error aleatorio**: el arranque
tardío afecta a ~37 % de los pacientes del hospital A y a solo ~6 % del B. La duración mediana
de la estancia es prácticamente la misma en ambos grupos, así que no se trata de pacientes
distintos, sino de **cómo cada hospital registró las primeras horas**.

Tres consecuencias prácticas que arrastramos al resto del proyecto:

1. **`ICULOS` sigue siendo un reloj válido**: mide horas reales desde el ingreso a UCI, y que
   falten las primeras filas no lo desplaza. No hay que reindexar nada.
2. **El "basal" del paciente hay que definirlo con cuidado**: en el notebook 05 calcularemos la
   desviación respecto a las primeras horas registradas. Para estos pacientes esas no son las
   primeras horas *reales* de UCI. Lo dejamos anotado como limitación explícita.
3. **Es la primera evidencia dura del *shift* entre hospitales.** Antes de mirar ni un signo
   vital ya sabemos que A y B no registran igual. Esto justifica por sí solo la estrategia de
   validación cruzada entre hospitales que aplicaremos en el notebook 06.

Guardamos el marcador para poder usarlo después como variable de control.

### 4.2 ¿La etiqueta es monótona?

`SepsisLabel` debería activarse una vez y quedarse en 1 hasta el alta: la sepsis no "se apaga"
dentro de la definición del challenge. Si encontráramos transiciones 1 → 0, el momento de
inicio del evento sería ambiguo y el utility score (que localiza el inicio con el primer 1)
daría resultados sin sentido.

In [8]:
# Buscamos cualquier transición de 1 a 0 dentro de un mismo paciente
cambios = df.groupby("pid", observed=True)["SepsisLabel"].diff()
n_apagados = int((cambios == -1).sum())
print(f"Transiciones 1 -> 0 encontradas: {n_apagados}")

Transiciones 1 -> 0 encontradas: 0

### 4.3 ¿Las variables demográficas son constantes por paciente?

`Age`, `Gender` y `HospAdmTime` describen al paciente, no a la hora. Si son constantes podemos
tratarlas aparte (sin ingeniería temporal) y usarlas para construir la tabla de pacientes del
dashboard. Conviene comprobarlo en vez de darlo por hecho.

In [9]:
demograficas = ["Age", "Gender", "HospAdmTime", "Unit1", "Unit2"]
variabilidad = df.groupby("pid", observed=True)[demograficas].nunique(dropna=True).max()
variabilidad.rename("máx. valores distintos dentro de un paciente").to_frame()

             máx. valores distintos dentro de un paciente
Age                                                     1
Gender                                                  1
HospAdmTime                                             1
Unit1                                                   1
Unit2                                                   1

### 4.4 ¿Hay valores clínicamente imposibles?

Antes de imputar cualquier cosa hay que saber si hay valores que directamente no pueden
existir en un ser humano. Un `O2Sat` de 120 % o una frecuencia cardiaca negativa serían errores
de registro, no variabilidad biológica, y arrastrarlos contaminaría medias y desviaciones.

Definimos rangos fisiológicos generosos a propósito: buscamos **imposibles**, no atípicos.
Un paciente de UCI con una frecuencia cardiaca de 180 está grave, pero es real y no se toca.

In [10]:
rangos_posibles = {
    "HR": (10, 300), "O2Sat": (0, 100), "Temp": (20, 45), "SBP": (20, 300),
    "MAP": (10, 250), "DBP": (10, 200), "Resp": (0, 80), "pH": (6.5, 8.0),
    "Glucose": (10, 1500), "Age": (0, 120),
}

fuera_de_rango = {}
for col, (lo, hi) in rangos_posibles.items():
    n = int(((df[col] < lo) | (df[col] > hi)).sum())
    if n:
        fuera_de_rango[col] = {"n_valores": n,
                               "porcentaje_": round(n / df[col].notna().sum() * 100, 4)}

pd.DataFrame(fuera_de_rango).T if fuera_de_rango else "Ningún valor fuera de los rangos fisiológicos posibles."

      n_valores  porcentaje_
Temp        2.0       0.0004
MAP       201.0       0.0148
DBP       103.0       0.0097
Resp       50.0       0.0038

Aparecen 356 valores sospechosos sobre 1,5 millones de filas. Son cantidades ínfimas, pero
antes de decidir qué hacer con ellos hay que **mirarlos**, porque "fuera de mi umbral
arbitrario" no es lo mismo que "imposible":

In [11]:
# ¿Qué valores concretos son? Un umbral redondo puede estar marcando valores extremos pero reales.
for col, (lo, hi) in rangos_posibles.items():
    extremos = df.loc[(df[col] < lo) | (df[col] > hi), col]
    if len(extremos):
        print(f"{col:10s} n={len(extremos):4d}  rango observado: {extremos.min():.1f} — {extremos.max():.1f}")

Temp       n=   2  rango observado: 50.0 — 50.0
MAP        n= 201  rango observado: 251.0 — 300.0
DBP        n= 103  rango observado: 201.0 — 300.0
Resp       n=  50  rango observado: 81.0 — 100.0

Ahora se puede decidir con criterio, y el criterio es distinto según el caso:

- **`Temp` = 50 °C** (2 registros): incompatible con la vida, sin ambigüedad posible. Es un
  error de digitación.
- **`MAP` y `DBP` que llegan exactamente hasta 300,0 mmHg**: el tope redondo e idéntico en ambas
  variables es la pista. No es casualidad fisiológica, es el límite de escala del monitor: el
  sensor satura y reporta su máximo. Además, una presión arterial media de 300 mmHg implicaría
  una sistólica aún mayor, algo incompatible con un paciente vivo. Artefacto típico de una línea
  arterial mal calibrada o purgada.
- **`Resp` entre 81 y 100** respiraciones por minuto: una taquipnea extrema real llega a ~60. Por
  encima de 80 lo que suele estar midiendo el monitor es movimiento del paciente, no ventilación.

**Decisión: convertir estos 356 valores a nulo, no eliminar las filas.** El razonamiento importa:
la fila contiene además frecuencia cardiaca, saturación y otras variables perfectamente válidas
de esa hora. Borrarla completa tiraría datos buenos por culpa de una sola celda mala. Al marcar
solo la celda como nula, el valor entra al mismo tratamiento de nulos que el resto y no
contamina medias ni desviaciones.

Es la única modificación de datos de este notebook, y es corrección de errores de registro,
no una decisión analítica.

In [12]:
n_antes = int(df[list(rangos_posibles)].notna().sum().sum())

for col, (lo, hi) in rangos_posibles.items():
    df.loc[(df[col] < lo) | (df[col] > hi), col] = pd.NA

n_despues = int(df[list(rangos_posibles)].notna().sum().sum())
print(f"Mediciones anuladas: {n_antes - n_despues} de {n_antes:,} "
      f"({(n_antes - n_despues) / n_antes * 100:.4f} % del total)")

Mediciones anuladas: 356 de 10,263,226 (0.0035 % del total)

## 5. Persistencia

Guardamos en **parquet** y no en CSV por dos razones concretas: el CSV perdería los tipos que
acabamos de fijar (todo volvería a `float64` y `object` al releer, deshaciendo el ahorro de
memoria) y pesaría varias veces más para 1,5 millones de filas.

Este archivo es el **punto de entrada único** de todos los notebooks siguientes: ninguno vuelve
a leer los `.psv`. Así garantizamos que todos trabajan exactamente sobre los mismos datos.

In [13]:
destino = io_datos.guardar_cohorte(df, cfg)
print(f"Guardado en {destino.relative_to(cfg['raiz'])} ({destino.stat().st_size / 1024**2:.0f} MB)")

Guardado en data\interim\cohorte_horaria.parquet (16 MB)

## 6. Qué sabemos al cerrar este notebook

**Estructura confirmada:** 40.336 pacientes repartidos casi por igual entre dos hospitales
(20.336 en A, 20.000 en B), 1.552.210 filas-hora, 40 variables clínicas más la etiqueta.

**Supuestos que se cumplen:** `ICULOS` es contiguo y está ordenado dentro de cada paciente — las
ventanas rodantes son válidas. `SepsisLabel` nunca pasa de 1 a 0, así que el inicio del evento
está bien definido y el utility score podrá localizarlo. `Age`, `Gender` y `HospAdmTime` son
constantes por paciente y pueden tratarse como atributos, no como series.

**Dos hallazgos que no esperábamos** y que cambian cosas más adelante:

1. **El 21,8 % de los pacientes no tiene registradas sus primeras horas de UCI**, y el fenómeno
   está muy concentrado en el hospital A (37 % vs 6 %). Es la primera evidencia de que los dos
   hospitales no registran igual, y obliga a matizar cómo definimos el "basal" de un paciente.
2. **356 mediciones fisiológicamente imposibles** (Temp de 50 °C, presiones y frecuencias
   respiratorias de artefacto). Se anularon las celdas, no las filas, para no descartar las
   mediciones válidas que las acompañan.

**El reto que ya se ve venir:** el registro es extremadamente disperso. Un paciente tiene sus
signos vitales casi cada hora, pero sus laboratorios aparecen unas pocas veces en toda la
estancia. Cuantificarlo bien y decidir qué hacer con ello es el trabajo del notebook 02, que es
donde de verdad se decide la calidad de este proyecto.

**Alcance de lo que se modificó aquí:** solo esas 356 celdas, que son errores de registro
inequívocos. Ninguna imputación, ninguna fila eliminada, ninguna variable transformada. Toda
decisión analítica queda para los notebooks siguientes, documentada donde se toma.